const regularCanadianCoins = [
  {
    value: "1 cent",
    collectionSet: "Canada Circulation",
    material: "Copper / copper-plated zinc",
    items: [
      ["1952-2002", 0, "", "images/coins/Canada/1-cent/canada-2010-1-cent-front.transparent.png", "images/coins/Canada/1-cent/canada-2010-1-cent-back.transparent.png"], ["1965", 0, "", "images/coins/Canada/1-cent/canada-1965-1-cent-front.transparent.png", "images/coins/Canada/1-cent/canada-1965-1-cent-back.transparent.png"], ["1974", 0, "", "images/coins/Canada/1-cent/canada-1974-1-cent-front.transparent.png", "images/coins/Canada/1-cent/canada-1974-1-cent-back.transparent.png"], ["1978", 0, "", "images/coins/Canada/1-cent/canada-1978-1-cent-front.transparent.png", "images/coins/Canada/1-cent/canada-1978-1-cent-back.transparent.png"], ["1981", 0, "", "images/coins/Canada/1-cent/canada-1981-1-cent-front.transparent.png", "images/coins/Canada/1-cent/canada-1981-1-cent-back.transparent.png"], ["1982", 0, "", "images/coins/Canada/1-cent/canada-1982-1-cent-front.transparent.png", "images/coins/Canada/1-cent/canada-1982-1-cent-back.transparent.png"], ["1985", 0, "", "images/coins/Canada/1-cent/canada-1985-1-cent-front.transparent.png", "images/coins/Canada/1-cent/canada-1985-1-cent-back.transparent.png"], ["1986", 1, "", "images/coins/Canada/1-cent/canada-1986-1-cent-front.transparent.png", "images/coins/Canada/1-cent/canada-1986-1-cent-back.transparent.png"], ["1987", 0, "", "images/coins/Canada/1-cent/canada-1987-1-cent-front.transparent.png", "images/coins/Canada/1-cent/canada-1987-1-cent-back.transparent.png"], ["1994", 0, "", "images/coins/Canada/1-cent/canada-1994-1-cent-front.transparent.png", "images/coins/Canada/1-cent/canada-1994-1-cent-back.transparent.png"], ["1996", 0, "", "images/coins/Canada/1-cent/canada-1996-1-cent-front.transparent.png", "images/coins/Canada/1-cent/canada-1996-1-cent-back.transparent.png"],
      ["2003", 0, "", "images/coins/Canada/1-cent/canada-2003-1-cent-front.transparent.png", "images/coins/Canada/1-cent/canada-2003-1-cent-back.transparent.png"], ["2004", 0, "", "images/coins/Canada/1-cent/canada-2004-1-cent-front.transparent.png", "images/coins/Canada/1-cent/canada-2004-1-cent-back.transparent.png"], ["2005", 1, "", "images/coins/Canada/1-cent/canada-2005-1-cent-front.transparent.png", "images/coins/Canada/1-cent/canada-2005-1-cent-back.transparent.png"], ["2006", 1, "", "images/coins/Canada/1-cent/canada-2006-1-cent-front.transparent.png", "images/coins/Canada/1-cent/canada-2006-1-cent-back.transparent.png"], ["2007", 2, "", "images/coins/Canada/1-cent/canada-2007-1-cent-front.transparent.png", "images/coins/Canada/1-cent/canada-2007-1-cent-back.transparent.png"], ["2008", 1, "", "images/coins/Canada/1-cent/canada-2008-1-cent-front.transparent.png", "images/coins/Canada/1-cent/canada-2008-1-cent-back.transparent.png"], ["2009", 2, "", "images/coins/Canada/1-cent/canada-2009-1-cent-front.transparent.png", "images/coins/Canada/1-cent/canada-2009-1-cent-back.transparent.png"], ["2010", 0, "", "images/coins/Canada/1-cent/canada-2010-1-cent-front.transparent.png", "images/coins/Canada/1-cent/canada-2010-1-cent-back.transparent.png"], ["2019", 0, "", "images/coins/Canada/1-cent/canada-2010-1-cent-front.transparent.png", "images/coins/Canada/1-cent/canada-2010-1-cent-back.transparent.png"],
      ["1867-2017", 0, "Canada 150", "images/coins/Canada/1-cent/canada-2010-1-cent-front.transparent.png", "images/coins/Canada/1-cent/canada-2010-1-cent-back.transparent.png"]
    ]
  },
  {
    value: "5 cents",
    collectionSet: "Canada Circulation",
    material: "Nickel / plated steel",
    items: [
      ["1867-1997", 0, "", "images/coins/Canada/5-cents/canada-1970s-1980s-5-cents-front.transparent.png", "images/coins/Canada/5-cents/canada-1970s-1980s-5-cents-back.transparent.png"], ["1952-2002", 2, "", "images/coins/Canada/5-cents/canada-1970s-1980s-5-cents-front.transparent.png", "images/coins/Canada/5-cents/canada-1970s-1980s-5-cents-back.transparent.png"], ["1969", 0, "", "images/coins/Canada/5-cents/canada-1969-5-cents-front.transparent.png", "images/coins/Canada/5-cents/canada-1969-5-cents-back.transparent.png"], ["1973", 0, "", "images/coins/Canada/5-cents/canada-1970s-1980s-5-cents-front.transparent.png", "images/coins/Canada/5-cents/canada-1970s-1980s-5-cents-back.transparent.png"], ["1979", 0, "", "images/coins/Canada/5-cents/canada-1970s-1980s-5-cents-front.transparent.png", "images/coins/Canada/5-cents/canada-1970s-1980s-5-cents-back.transparent.png"], ["1981", 1, "", "images/coins/Canada/5-cents/canada-1970s-1980s-5-cents-front.transparent.png", "images/coins/Canada/5-cents/canada-1970s-1980s-5-cents-back.transparent.png"], ["1984", 1, "", "images/coins/Canada/5-cents/canada-1970s-1980s-5-cents-front.transparent.png", "images/coins/Canada/5-cents/canada-1970s-1980s-5-cents-back.transparent.png"], ["1986", 0, "", "images/coins/Canada/5-cents/canada-1970s-1980s-5-cents-front.transparent.png", "images/coins/Canada/5-cents/canada-1970s-1980s-5-cents-back.transparent.png"], ["1987", 0, "", "images/coins/Canada/5-cents/canada-1970s-1980s-5-cents-front.transparent.png", "images/coins/Canada/5-cents/canada-1970s-1980s-5-cents-back.transparent.png"], ["1989", 0, "", "images/coins/Canada/5-cents/canada-1970s-1980s-5-cents-front.transparent.png", "images/coins/Canada/5-cents/canada-1970s-1980s-5-cents-back.transparent.png"],
      ["1990", 1, "", "images/coins/Canada/5-cents/canada-1970s-1980s-5-cents-front.transparent.png", "images/coins/Canada/5-cents/canada-1970s-1980s-5-cents-back.transparent.png"], ["1996", 0, "", "images/coins/Canada/5-cents/canada-1970s-1980s-5-cents-front.transparent.png", "images/coins/Canada/5-cents/canada-1970s-1980s-5-cents-back.transparent.png"], ["1997", 0, "", "images/coins/Canada/5-cents/canada-1970s-1980s-5-cents-front.transparent.png", "images/coins/Canada/5-cents/canada-1970s-1980s-5-cents-back.transparent.png"], ["1998", 0, "", "images/coins/Canada/5-cents/canada-1970s-1980s-5-cents-front.transparent.png", "images/coins/Canada/5-cents/canada-1970s-1980s-5-cents-back.transparent.png"], ["1999", 1, "", "images/coins/Canada/5-cents/canada-1970s-1980s-5-cents-front.transparent.png", "images/coins/Canada/5-cents/canada-1970s-1980s-5-cents-back.transparent.png"], ["2000", 1, "", "images/coins/Canada/5-cents/canada-1970s-1980s-5-cents-front.transparent.png", "images/coins/Canada/5-cents/canada-1970s-1980s-5-cents-back.transparent.png"], ["2001", 2, "", "images/coins/Canada/5-cents/canada-1970s-1980s-5-cents-front.transparent.png", "images/coins/Canada/5-cents/canada-1970s-1980s-5-cents-back.transparent.png"], ["2003", 1, "", "images/coins/Canada/5-cents/canada-1970s-1980s-5-cents-front.transparent.png", "images/coins/Canada/5-cents/canada-1970s-1980s-5-cents-back.transparent.png"], ["2004", 1, "", "images/coins/Canada/5-cents/canada-1970s-1980s-5-cents-front.transparent.png", "images/coins/Canada/5-cents/canada-1970s-1980s-5-cents-back.transparent.png"],
      ["2005", 2, "", "images/coins/Canada/5-cents/canada-1970s-1980s-5-cents-front.transparent.png", "images/coins/Canada/5-cents/canada-1970s-1980s-5-cents-back.transparent.png"], ["2006", 1, "", "images/coins/Canada/5-cents/canada-1970s-1980s-5-cents-front.transparent.png", "images/coins/Canada/5-cents/canada-1970s-1980s-5-cents-back.transparent.png"], ["2007", 1, "", "images/coins/Canada/5-cents/canada-1970s-1980s-5-cents-front.transparent.png", "images/coins/Canada/5-cents/canada-1970s-1980s-5-cents-back.transparent.png"], ["2008", 1, "", "images/coins/Canada/5-cents/canada-1970s-1980s-5-cents-front.transparent.png", "images/coins/Canada/5-cents/canada-1970s-1980s-5-cents-back.transparent.png"], ["2009", 2, "", "images/coins/Canada/5-cents/canada-1970s-1980s-5-cents-front.transparent.png", "images/coins/Canada/5-cents/canada-1970s-1980s-5-cents-back.transparent.png"], ["2010", 2, "", "images/coins/Canada/5-cents/canada-1970s-1980s-5-cents-front.transparent.png", "images/coins/Canada/5-cents/canada-1970s-1980s-5-cents-back.transparent.png"], ["2011", 1, "", "images/coins/Canada/5-cents/canada-1970s-1980s-5-cents-front.transparent.png", "images/coins/Canada/5-cents/canada-1970s-1980s-5-cents-back.transparent.png"], ["2012", 1, "", "images/coins/Canada/5-cents/canada-1970s-1980s-5-cents-front.transparent.png", "images/coins/Canada/5-cents/canada-1970s-1980s-5-cents-back.transparent.png"],
      ["2013", 1, "", "images/coins/Canada/5-cents/canada-1970s-1980s-5-cents-front.transparent.png", "images/coins/Canada/5-cents/canada-1970s-1980s-5-cents-back.transparent.png"], ["2014", 2, "", "images/coins/Canada/5-cents/canada-1970s-1980s-5-cents-front.transparent.png", "images/coins/Canada/5-cents/canada-1970s-1980s-5-cents-back.transparent.png"], ["2015", 1, "", "images/coins/Canada/5-cents/canada-1970s-1980s-5-cents-front.transparent.png", "images/coins/Canada/5-cents/canada-1970s-1980s-5-cents-back.transparent.png"], ["2016", 1, "", "images/coins/Canada/5-cents/canada-1970s-1980s-5-cents-front.transparent.png", "images/coins/Canada/5-cents/canada-1970s-1980s-5-cents-back.transparent.png"], ["2018", 1, "", "images/coins/Canada/5-cents/canada-1970s-1980s-5-cents-front.transparent.png", "images/coins/Canada/5-cents/canada-1970s-1980s-5-cents-back.transparent.png"], ["2019", 1, "", "images/coins/Canada/5-cents/canada-1970s-1980s-5-cents-front.transparent.png", "images/coins/Canada/5-cents/canada-1970s-1980s-5-cents-back.transparent.png"], ["2021", 1, "", "images/coins/Canada/5-cents/canada-1970s-1980s-5-cents-front.transparent.png", "images/coins/Canada/5-cents/canada-1970s-1980s-5-cents-back.transparent.png"], ["2022", 0, "", "images/coins/Canada/5-cents/canada-1970s-1980s-5-cents-front.transparent.png", "images/coins/Canada/5-cents/canada-1970s-1980s-5-cents-back.transparent.png"], ["2024", 0, "", "images/coins/Canada/5-cents/canada-1970s-1980s-5-cents-front.transparent.png", "images/coins/Canada/5-cents/canada-1970s-1980s-5-cents-back.transparent.png"],
      ["1949", 0, "", "images/coins/Canada/5-cents/canada-1949-5-cents-front.transparent.png", "images/coins/Canada/5-cents/canada-1949-5-cents-back.transparent.png"]
    ]
  },
  {
    value: "10 cents",
    collectionSet: "Canada Circulation",
    material: "Nickel / plated steel",
    items: [
      ["1867-1967", 0, "", "images/coins/Canada/10-cents/canada-1967-10-cents-front.transparent.png", "images/coins/Canada/10-cents/canada-1967-10-cents-back.transparent.png"], ["1921-2021", 2, "", "images/coins/Canada/10-cents/canada-1970s-1980s-10-cents-front.transparent.png", "images/coins/Canada/10-cents/canada-1970s-1980s-10-cents-back.transparent.png"], ["1943", 0, "", "images/coins/Canada/10-cents/canada-1943-10-cents-front.transparent.png", "images/coins/Canada/10-cents/canada-1943-10-cents-back.transparent.png"], ["1952-2002", 0, "", "images/coins/Canada/10-cents/canada-1970s-1980s-10-cents-front.transparent.png", "images/coins/Canada/10-cents/canada-1970s-1980s-10-cents-back.transparent.png"], ["1968", 0, "", "images/coins/Canada/10-cents/canada-1968-10-cents-front.transparent.png", "images/coins/Canada/10-cents/canada-1968-10-cents-back.transparent.png"], ["1973", 0, "", "images/coins/Canada/10-cents/canada-1970s-1980s-10-cents-front.transparent.png", "images/coins/Canada/10-cents/canada-1970s-1980s-10-cents-back.transparent.png"], ["1974", 0, "", "images/coins/Canada/10-cents/canada-1970s-1980s-10-cents-front.transparent.png", "images/coins/Canada/10-cents/canada-1970s-1980s-10-cents-back.transparent.png"], ["1975", 0, "", "images/coins/Canada/10-cents/canada-1970s-1980s-10-cents-front.transparent.png", "images/coins/Canada/10-cents/canada-1970s-1980s-10-cents-back.transparent.png"], ["1977", 0, "", "images/coins/Canada/10-cents/canada-1970s-1980s-10-cents-front.transparent.png", "images/coins/Canada/10-cents/canada-1970s-1980s-10-cents-back.transparent.png"], ["1979", 0, "", "images/coins/Canada/10-cents/canada-1970s-1980s-10-cents-front.transparent.png", "images/coins/Canada/10-cents/canada-1970s-1980s-10-cents-back.transparent.png"],
      ["1980", 0, "", "images/coins/Canada/10-cents/canada-1970s-1980s-10-cents-front.transparent.png", "images/coins/Canada/10-cents/canada-1970s-1980s-10-cents-back.transparent.png"], ["1984", 0, "", "images/coins/Canada/10-cents/canada-1970s-1980s-10-cents-front.transparent.png", "images/coins/Canada/10-cents/canada-1970s-1980s-10-cents-back.transparent.png"], ["1985", 0, "", "images/coins/Canada/10-cents/canada-1970s-1980s-10-cents-front.transparent.png", "images/coins/Canada/10-cents/canada-1970s-1980s-10-cents-back.transparent.png"], ["1986", 0, "", "images/coins/Canada/10-cents/canada-1970s-1980s-10-cents-front.transparent.png", "images/coins/Canada/10-cents/canada-1970s-1980s-10-cents-back.transparent.png"], ["1988", 0, "", "images/coins/Canada/10-cents/canada-1970s-1980s-10-cents-front.transparent.png", "images/coins/Canada/10-cents/canada-1970s-1980s-10-cents-back.transparent.png"], ["1989", 1, "", "images/coins/Canada/10-cents/canada-1970s-1980s-10-cents-front.transparent.png", "images/coins/Canada/10-cents/canada-1970s-1980s-10-cents-back.transparent.png"], ["1992", 0, "", "images/coins/Canada/10-cents/canada-1970s-1980s-10-cents-front.transparent.png", "images/coins/Canada/10-cents/canada-1970s-1980s-10-cents-back.transparent.png"], ["1997", 0, "", "images/coins/Canada/10-cents/canada-1970s-1980s-10-cents-front.transparent.png", "images/coins/Canada/10-cents/canada-1970s-1980s-10-cents-back.transparent.png"], ["1998", 1, "", "images/coins/Canada/10-cents/canada-1970s-1980s-10-cents-front.transparent.png", "images/coins/Canada/10-cents/canada-1970s-1980s-10-cents-back.transparent.png"], ["1999", 1, "", "images/coins/Canada/10-cents/canada-1970s-1980s-10-cents-front.transparent.png", "images/coins/Canada/10-cents/canada-1970s-1980s-10-cents-back.transparent.png"],
      ["2000", 0, "", "images/coins/Canada/10-cents/canada-1970s-1980s-10-cents-front.transparent.png", "images/coins/Canada/10-cents/canada-1970s-1980s-10-cents-back.transparent.png"], ["2001", 2, "", "images/coins/Canada/10-cents/canada-1970s-1980s-10-cents-front.transparent.png", "images/coins/Canada/10-cents/canada-1970s-1980s-10-cents-back.transparent.png"], ["2003", 0, "", "images/coins/Canada/10-cents/canada-1970s-1980s-10-cents-front.transparent.png", "images/coins/Canada/10-cents/canada-1970s-1980s-10-cents-back.transparent.png"], ["2004", 1, "", "images/coins/Canada/10-cents/canada-1970s-1980s-10-cents-front.transparent.png", "images/coins/Canada/10-cents/canada-1970s-1980s-10-cents-back.transparent.png"], ["2005", 0, "", "images/coins/Canada/10-cents/canada-1970s-1980s-10-cents-front.transparent.png", "images/coins/Canada/10-cents/canada-1970s-1980s-10-cents-back.transparent.png"], ["2006", 1, "", "images/coins/Canada/10-cents/canada-1970s-1980s-10-cents-front.transparent.png", "images/coins/Canada/10-cents/canada-1970s-1980s-10-cents-back.transparent.png"], ["2007", 1, "", "images/coins/Canada/10-cents/canada-1970s-1980s-10-cents-front.transparent.png", "images/coins/Canada/10-cents/canada-1970s-1980s-10-cents-back.transparent.png"], ["2008", 1, "", "images/coins/Canada/10-cents/canada-1970s-1980s-10-cents-front.transparent.png", "images/coins/Canada/10-cents/canada-1970s-1980s-10-cents-back.transparent.png"], ["2009", 1, "", "images/coins/Canada/10-cents/canada-1970s-1980s-10-cents-front.transparent.png", "images/coins/Canada/10-cents/canada-1970s-1980s-10-cents-back.transparent.png"],
      ["2010", 0, "", "images/coins/Canada/10-cents/canada-1970s-1980s-10-cents-front.transparent.png", "images/coins/Canada/10-cents/canada-1970s-1980s-10-cents-back.transparent.png"], ["2011", 1, "", "images/coins/Canada/10-cents/canada-1970s-1980s-10-cents-front.transparent.png", "images/coins/Canada/10-cents/canada-1970s-1980s-10-cents-back.transparent.png"], ["2012", 1, "", "images/coins/Canada/10-cents/canada-1970s-1980s-10-cents-front.transparent.png", "images/coins/Canada/10-cents/canada-1970s-1980s-10-cents-back.transparent.png"], ["2013", 0, "", "images/coins/Canada/10-cents/canada-1970s-1980s-10-cents-front.transparent.png", "images/coins/Canada/10-cents/canada-1970s-1980s-10-cents-back.transparent.png"], ["2014", 0, "", "images/coins/Canada/10-cents/canada-1970s-1980s-10-cents-front.transparent.png", "images/coins/Canada/10-cents/canada-1970s-1980s-10-cents-back.transparent.png"], ["2015", 0, "", "images/coins/Canada/10-cents/canada-1970s-1980s-10-cents-front.transparent.png", "images/coins/Canada/10-cents/canada-1970s-1980s-10-cents-back.transparent.png"], ["2016", 1, "", "images/coins/Canada/10-cents/canada-1970s-1980s-10-cents-front.transparent.png", "images/coins/Canada/10-cents/canada-1970s-1980s-10-cents-back.transparent.png"], ["2018", 1, "", "images/coins/Canada/10-cents/canada-1970s-1980s-10-cents-front.transparent.png", "images/coins/Canada/10-cents/canada-1970s-1980s-10-cents-back.transparent.png"], ["2019", 1, "", "images/coins/Canada/10-cents/canada-1970s-1980s-10-cents-front.transparent.png", "images/coins/Canada/10-cents/canada-1970s-1980s-10-cents-back.transparent.png"], ["2020", 1, "", "images/coins/Canada/10-cents/canada-1970s-1980s-10-cents-front.transparent.png", "images/coins/Canada/10-cents/canada-1970s-1980s-10-cents-back.transparent.png"], ["2021", 1, "", "images/coins/Canada/10-cents/canada-1970s-1980s-10-cents-front.transparent.png", "images/coins/Canada/10-cents/canada-1970s-1980s-10-cents-back.transparent.png"],
      ["2022", 0, "", "images/coins/Canada/10-cents/canada-1970s-1980s-10-cents-front.transparent.png", "images/coins/Canada/10-cents/canada-1970s-1980s-10-cents-back.transparent.png"], ["2024", 0, "", "images/coins/Canada/10-cents/canada-1970s-1980s-10-cents-front.transparent.png", "images/coins/Canada/10-cents/canada-1970s-1980s-10-cents-back.transparent.png"], ["2025", 0, "", "images/coins/Canada/10-cents/canada-1970s-1980s-10-cents-front.transparent.png", "images/coins/Canada/10-cents/canada-1970s-1980s-10-cents-back.transparent.png"]
    ]
  },
  {
    value: "25 cents",
    collectionSet: "Canada Circulation",
    material: "Nickel / plated steel",
    items: [
      ["1971", 0, "", "images/coins/Canada/5-cents/canada-1970s-1980s-25-cents-front.transparent.png", "images/coins/Canada/5-cents/canada-1970s-1980s-25-cents-back.transparent.png"], ["1974", 0, "", "images/coins/Canada/5-cents/canada-1970s-1980s-25-cents-front.transparent.png", "images/coins/Canada/5-cents/canada-1970s-1980s-25-cents-back.transparent.png"], ["1975", 0, "", "images/coins/Canada/5-cents/canada-1970s-1980s-25-cents-front.transparent.png", "images/coins/Canada/5-cents/canada-1970s-1980s-25-cents-back.transparent.png"], ["1976", 0, "", "images/coins/Canada/5-cents/canada-1970s-1980s-25-cents-front.transparent.png", "images/coins/Canada/5-cents/canada-1970s-1980s-25-cents-back.transparent.png"], ["1979", 1, "", "images/coins/Canada/5-cents/canada-1970s-1980s-25-cents-front.transparent.png", "images/coins/Canada/5-cents/canada-1970s-1980s-25-cents-back.transparent.png"], ["1985", 1, "", "images/coins/Canada/5-cents/canada-1970s-1980s-25-cents-front.transparent.png", "images/coins/Canada/5-cents/canada-1970s-1980s-25-cents-back.transparent.png"], ["1989", 0, "", "images/coins/Canada/5-cents/canada-1970s-1980s-25-cents-front.transparent.png", "images/coins/Canada/5-cents/canada-1970s-1980s-25-cents-back.transparent.png"], ["1990", 0, "", "images/coins/Canada/5-cents/canada-1970s-1980s-25-cents-front.transparent.png", "images/coins/Canada/5-cents/canada-1970s-1980s-25-cents-back.transparent.png"], ["1993", 0, "", "images/coins/Canada/5-cents/canada-1970s-1980s-25-cents-front.transparent.png", "images/coins/Canada/5-cents/canada-1970s-1980s-25-cents-back.transparent.png"], ["1994", 0, "", "images/coins/Canada/5-cents/canada-1970s-1980s-25-cents-front.transparent.png", "images/coins/Canada/5-cents/canada-1970s-1980s-25-cents-back.transparent.png"], ["1995", 0, "", "images/coins/Canada/5-cents/canada-1970s-1980s-25-cents-front.transparent.png", "images/coins/Canada/5-cents/canada-1970s-1980s-25-cents-back.transparent.png"], ["1996", 0, "", "images/coins/Canada/5-cents/canada-1970s-1980s-25-cents-front.transparent.png", "images/coins/Canada/5-cents/canada-1970s-1980s-25-cents-back.transparent.png"], ["1997", 0, "", "images/coins/Canada/5-cents/canada-1970s-1980s-25-cents-front.transparent.png", "images/coins/Canada/5-cents/canada-1970s-1980s-25-cents-back.transparent.png"], ["1998", 0, "", "images/coins/Canada/5-cents/canada-1970s-1980s-25-cents-front.transparent.png", "images/coins/Canada/5-cents/canada-1970s-1980s-25-cents-back.transparent.png"], ["1999", 0, "", "images/coins/Canada/5-cents/canada-1970s-1980s-25-cents-front.transparent.png", "images/coins/Canada/5-cents/canada-1970s-1980s-25-cents-back.transparent.png"],
      ["1952-2002", 2, "", "images/coins/Canada/5-cents/canada-1970s-1980s-25-cents-front.transparent.png", "images/coins/Canada/5-cents/canada-1970s-1980s-25-cents-back.transparent.png"], ["2003", 1, "", "images/coins/Canada/5-cents/canada-1970s-1980s-25-cents-front.transparent.png", "images/coins/Canada/5-cents/canada-1970s-1980s-25-cents-back.transparent.png"], ["2004", 1, "", "images/coins/Canada/5-cents/canada-1970s-1980s-25-cents-front.transparent.png", "images/coins/Canada/5-cents/canada-1970s-1980s-25-cents-back.transparent.png"], ["2005", 2, "", "images/coins/Canada/5-cents/canada-1970s-1980s-25-cents-front.transparent.png", "images/coins/Canada/5-cents/canada-1970s-1980s-25-cents-back.transparent.png"], ["2006", 2, "", "images/coins/Canada/5-cents/canada-1970s-1980s-25-cents-front.transparent.png", "images/coins/Canada/5-cents/canada-1970s-1980s-25-cents-back.transparent.png"], ["2007", 1, "", "images/coins/Canada/5-cents/canada-1970s-1980s-25-cents-front.transparent.png", "images/coins/Canada/5-cents/canada-1970s-1980s-25-cents-back.transparent.png"], ["2008", 0, "", "images/coins/Canada/5-cents/canada-1970s-1980s-25-cents-front.transparent.png", "images/coins/Canada/5-cents/canada-1970s-1980s-25-cents-back.transparent.png"], ["2009", 0, "", "images/coins/Canada/5-cents/canada-1970s-1980s-25-cents-front.transparent.png", "images/coins/Canada/5-cents/canada-1970s-1980s-25-cents-back.transparent.png"],
      ["2010", 1, "", "images/coins/Canada/5-cents/canada-1970s-1980s-25-cents-front.transparent.png", "images/coins/Canada/5-cents/canada-1970s-1980s-25-cents-back.transparent.png"], ["2011", 0, "", "images/coins/Canada/5-cents/canada-1970s-1980s-25-cents-front.transparent.png", "images/coins/Canada/5-cents/canada-1970s-1980s-25-cents-back.transparent.png"], ["2012", 2, "", "images/coins/Canada/5-cents/canada-1970s-1980s-25-cents-front.transparent.png", "images/coins/Canada/5-cents/canada-1970s-1980s-25-cents-back.transparent.png"], ["2014", 0, "", "images/coins/Canada/5-cents/canada-1970s-1980s-25-cents-front.transparent.png", "images/coins/Canada/5-cents/canada-1970s-1980s-25-cents-back.transparent.png"], ["2015", 1, "", "images/coins/Canada/5-cents/canada-1970s-1980s-25-cents-front.transparent.png", "images/coins/Canada/5-cents/canada-1970s-1980s-25-cents-back.transparent.png"], ["2016", 1, "", "images/coins/Canada/5-cents/canada-1970s-1980s-25-cents-front.transparent.png", "images/coins/Canada/5-cents/canada-1970s-1980s-25-cents-back.transparent.png"], ["2018", 1, "", "images/coins/Canada/5-cents/canada-1970s-1980s-25-cents-front.transparent.png", "images/coins/Canada/5-cents/canada-1970s-1980s-25-cents-back.transparent.png"], ["2019", 1, "", "images/coins/Canada/5-cents/canada-1970s-1980s-25-cents-front.transparent.png", "images/coins/Canada/5-cents/canada-1970s-1980s-25-cents-back.transparent.png"],
      ["2020", 2, "", "images/coins/Canada/5-cents/canada-1970s-1980s-25-cents-front.transparent.png", "images/coins/Canada/5-cents/canada-1970s-1980s-25-cents-back.transparent.png"], ["2021", 1, "", "images/coins/Canada/5-cents/canada-1970s-1980s-25-cents-front.transparent.png", "images/coins/Canada/5-cents/canada-1970s-1980s-25-cents-back.transparent.png"], ["2022", 1, "", "images/coins/Canada/5-cents/canada-1970s-1980s-25-cents-front.transparent.png", "images/coins/Canada/5-cents/canada-1970s-1980s-25-cents-back.transparent.png"], ["2023", 0, "", "images/coins/Canada/5-cents/canada-1970s-1980s-25-cents-front.transparent.png", "images/coins/Canada/5-cents/canada-1970s-1980s-25-cents-back.transparent.png"], ["2024", 1, "", "images/coins/Canada/5-cents/canada-1970s-1980s-25-cents-front.transparent.png", "images/coins/Canada/5-cents/canada-1970s-1980s-25-cents-back.transparent.png"], ["2025", 0, "", "images/coins/Canada/5-cents/canada-1970s-1980s-25-cents-front.transparent.png", "images/coins/Canada/5-cents/canada-1970s-1980s-25-cents-back.transparent.png"]
    ]
  },
  {
    value: "1 dollar",
    collectionSet: "Canada Circulation",
    material: "Bronze-plated nickel / brass-plated steel",
    items: [
      ["1987", 2, "", "images/coins/Canada/1-dollar/canada-1987-1989-1-dollar-front.transparent.png", "images/coins/Canada/1-dollar/canada-1987-1989-1-dollar-back.transparent.png"], ["1988", 2, "", "images/coins/Canada/1-dollar/canada-1987-1989-1-dollar-front.transparent.png", "images/coins/Canada/1-dollar/canada-1987-1989-1-dollar-back.transparent.png"], ["1989", 3, "", "images/coins/Canada/1-dollar/canada-1987-1989-1-dollar-front.transparent.png", "images/coins/Canada/1-dollar/canada-1987-1989-1-dollar-back.transparent.png"], ["1990", 2, "", "images/coins/Canada/1-dollar/canada-1987-1989-1-dollar-front.transparent.png", "images/coins/Canada/1-dollar/canada-1987-1989-1-dollar-back.transparent.png"], ["1991", 0, "", "images/coins/Canada/1-dollar/canada-1987-1989-1-dollar-front.transparent.png", "images/coins/Canada/1-dollar/canada-1987-1989-1-dollar-back.transparent.png"], ["1993", 0, "", "images/coins/Canada/1-dollar/canada-1987-1989-1-dollar-front.transparent.png", "images/coins/Canada/1-dollar/canada-1987-1989-1-dollar-back.transparent.png"], ["1995", 0, "", "images/coins/Canada/1-dollar/canada-1987-1989-1-dollar-front.transparent.png", "images/coins/Canada/1-dollar/canada-1987-1989-1-dollar-back.transparent.png"], ["2004", 0, "", "images/coins/Canada/1-dollar/canada-1987-1989-1-dollar-front.transparent.png", "images/coins/Canada/1-dollar/canada-1987-1989-1-dollar-back.transparent.png"], ["2008", 0, "", "images/coins/Canada/1-dollar/canada-1987-1989-1-dollar-front.transparent.png", "images/coins/Canada/1-dollar/canada-1987-1989-1-dollar-back.transparent.png"], ["2009", 1, "", "images/coins/Canada/1-dollar/canada-1987-1989-1-dollar-front.transparent.png", "images/coins/Canada/1-dollar/canada-1987-1989-1-dollar-back.transparent.png"],
      ["2012", 1, "", "images/coins/Canada/1-dollar/canada-1987-1989-1-dollar-front.transparent.png", "images/coins/Canada/1-dollar/canada-1987-1989-1-dollar-back.transparent.png"], ["2013", 1, "", "images/coins/Canada/1-dollar/canada-1987-1989-1-dollar-front.transparent.png", "images/coins/Canada/1-dollar/canada-1987-1989-1-dollar-back.transparent.png"], ["2014", 0, "", "images/coins/Canada/1-dollar/canada-1987-1989-1-dollar-front.transparent.png", "images/coins/Canada/1-dollar/canada-1987-1989-1-dollar-back.transparent.png"], ["2015", 2, "", "images/coins/Canada/1-dollar/canada-1987-1989-1-dollar-front.transparent.png", "images/coins/Canada/1-dollar/canada-1987-1989-1-dollar-back.transparent.png"], ["2016", 0, "", "images/coins/Canada/1-dollar/canada-1987-1989-1-dollar-front.transparent.png", "images/coins/Canada/1-dollar/canada-1987-1989-1-dollar-back.transparent.png"], ["2018", 1, "", "images/coins/Canada/1-dollar/canada-1987-1989-1-dollar-front.transparent.png", "images/coins/Canada/1-dollar/canada-1987-1989-1-dollar-back.transparent.png"], ["2019", 2, "", "images/coins/Canada/1-dollar/canada-1987-1989-1-dollar-front.transparent.png", "images/coins/Canada/1-dollar/canada-1987-1989-1-dollar-back.transparent.png"], ["2020", 0, "", "images/coins/Canada/1-dollar/canada-1987-1989-1-dollar-front.transparent.png", "images/coins/Canada/1-dollar/canada-1987-1989-1-dollar-back.transparent.png"], ["2021", 2, "", "images/coins/Canada/1-dollar/canada-1987-1989-1-dollar-front.transparent.png", "images/coins/Canada/1-dollar/canada-1987-1989-1-dollar-back.transparent.png"], ["2022", 2, "", "images/coins/Canada/1-dollar/canada-1987-1989-1-dollar-front.transparent.png", "images/coins/Canada/1-dollar/canada-1987-1989-1-dollar-back.transparent.png"], ["2023", 1, "", "images/coins/Canada/1-dollar/canada-1987-1989-1-dollar-front.transparent.png", "images/coins/Canada/1-dollar/canada-1987-1989-1-dollar-back.transparent.png"], ["2024", 1, "", "images/coins/Canada/1-dollar/canada-1987-1989-1-dollar-front.transparent.png", "images/coins/Canada/1-dollar/canada-1987-1989-1-dollar-back.transparent.png"], ["2025", 1, "", "images/coins/Canada/1-dollar/canada-1987-1989-1-dollar-front.transparent.png", "images/coins/Canada/1-dollar/canada-1987-1989-1-dollar-back.transparent.png"]
    ]
  },
  {
    value: "2 dollars",
    collectionSet: "Canada Circulation",
    material: "Bi-metallic",
    items: [
      ["1952-2002", 0, "", "images/coins/Canada/2-dollars/canada-1996-2003-2-dollars-front.transparent.png", "images/coins/Canada/2-dollars/canada-1996-2003-2-dollars-back.transparent.png"], ["1996", 1, "", "images/coins/Canada/2-dollars/canada-1996-2003-2-dollars-front.transparent.png", "images/coins/Canada/2-dollars/canada-1996-2003-2-dollars-back.transparent.png"], ["1997", 1, "", "images/coins/Canada/2-dollars/canada-1996-2003-2-dollars-front.transparent.png", "images/coins/Canada/2-dollars/canada-1996-2003-2-dollars-back.transparent.png"], ["1998", 0, "", "images/coins/Canada/2-dollars/canada-1996-2003-2-dollars-front.transparent.png", "images/coins/Canada/2-dollars/canada-1996-2003-2-dollars-back.transparent.png"], ["1999", 0, "", "images/coins/Canada/2-dollars/canada-1996-2003-2-dollars-front.transparent.png", "images/coins/Canada/2-dollars/canada-1996-2003-2-dollars-back.transparent.png"], ["2000", 0, "", "images/coins/Canada/2-dollars/canada-1996-2003-2-dollars-front.transparent.png", "images/coins/Canada/2-dollars/canada-1996-2003-2-dollars-back.transparent.png"], ["2001", 0, "", "images/coins/Canada/2-dollars/canada-1996-2003-2-dollars-front.transparent.png", "images/coins/Canada/2-dollars/canada-1996-2003-2-dollars-back.transparent.png"], ["2002", 0, "", "images/coins/Canada/2-dollars/canada-1996-2003-2-dollars-front.transparent.png", "images/coins/Canada/2-dollars/canada-1996-2003-2-dollars-back.transparent.png"], ["2003", 0, "", "images/coins/Canada/2-dollars/canada-1996-2003-2-dollars-front.transparent.png", "images/coins/Canada/2-dollars/canada-1996-2003-2-dollars-back.transparent.png"], ["2004", 0, "", "images/coins/Canada/2-dollars/canada-1996-2003-2-dollars-front.transparent.png", "images/coins/Canada/2-dollars/canada-1996-2003-2-dollars-back.transparent.png"], ["2005", 0, "", "images/coins/Canada/2-dollars/canada-1996-2003-2-dollars-front.transparent.png", "images/coins/Canada/2-dollars/canada-1996-2003-2-dollars-back.transparent.png"], ["2006", 0, "", "images/coins/Canada/2-dollars/canada-1996-2003-2-dollars-front.transparent.png", "images/coins/Canada/2-dollars/canada-1996-2003-2-dollars-back.transparent.png"], ["2007", 0, "", "images/coins/Canada/2-dollars/canada-1996-2003-2-dollars-front.transparent.png", "images/coins/Canada/2-dollars/canada-1996-2003-2-dollars-back.transparent.png"], ["2008", 0, "", "images/coins/Canada/2-dollars/canada-1996-2003-2-dollars-front.transparent.png", "images/coins/Canada/2-dollars/canada-1996-2003-2-dollars-back.transparent.png"], ["2009", 0, "", "images/coins/Canada/2-dollars/canada-1996-2003-2-dollars-front.transparent.png", "images/coins/Canada/2-dollars/canada-1996-2003-2-dollars-back.transparent.png"],
      ["2010", 0, "", "images/coins/Canada/2-dollars/canada-1996-2003-2-dollars-front.transparent.png", "images/coins/Canada/2-dollars/canada-1996-2003-2-dollars-back.transparent.png"], ["2011", 0, "", "images/coins/Canada/2-dollars/canada-1996-2003-2-dollars-front.transparent.png", "images/coins/Canada/2-dollars/canada-1996-2003-2-dollars-back.transparent.png"], ["2012", 2, "", "images/coins/Canada/2-dollars/canada-1996-2003-2-dollars-front.transparent.png", "images/coins/Canada/2-dollars/canada-1996-2003-2-dollars-back.transparent.png"], ["2013", 1, "", "images/coins/Canada/2-dollars/canada-1996-2003-2-dollars-front.transparent.png", "images/coins/Canada/2-dollars/canada-1996-2003-2-dollars-back.transparent.png"], ["2014", 0, "", "images/coins/Canada/2-dollars/canada-1996-2003-2-dollars-front.transparent.png", "images/coins/Canada/2-dollars/canada-1996-2003-2-dollars-back.transparent.png"], ["2015", 0, "", "images/coins/Canada/2-dollars/canada-1996-2003-2-dollars-front.transparent.png", "images/coins/Canada/2-dollars/canada-1996-2003-2-dollars-back.transparent.png"], ["2016", 0, "", "images/coins/Canada/2-dollars/canada-1996-2003-2-dollars-front.transparent.png", "images/coins/Canada/2-dollars/canada-1996-2003-2-dollars-back.transparent.png"], ["2018", 1, "", "images/coins/Canada/2-dollars/canada-1996-2003-2-dollars-front.transparent.png", "images/coins/Canada/2-dollars/canada-1996-2003-2-dollars-back.transparent.png"], ["2019", 0, "", "images/coins/Canada/2-dollars/canada-1996-2003-2-dollars-front.transparent.png", "images/coins/Canada/2-dollars/canada-1996-2003-2-dollars-back.transparent.png"], ["2020", 0, "", "images/coins/Canada/2-dollars/canada-1996-2003-2-dollars-front.transparent.png", "images/coins/Canada/2-dollars/canada-1996-2003-2-dollars-back.transparent.png"], ["2021", 0, "", "images/coins/Canada/2-dollars/canada-1996-2003-2-dollars-front.transparent.png", "images/coins/Canada/2-dollars/canada-1996-2003-2-dollars-back.transparent.png"], ["2022", 0, "", "images/coins/Canada/2-dollars/canada-1996-2003-2-dollars-front.transparent.png", "images/coins/Canada/2-dollars/canada-1996-2003-2-dollars-back.transparent.png"], ["2024", 0, "", "images/coins/Canada/2-dollars/canada-1996-2003-2-dollars-front.transparent.png", "images/coins/Canada/2-dollars/canada-1996-2003-2-dollars-back.transparent.png"], ["2025", 1, "", "images/coins/Canada/2-dollars/canada-1996-2003-2-dollars-front.transparent.png", "images/coins/Canada/2-dollars/canada-1996-2003-2-dollars-back.transparent.png"]
    ]
  }
];

const specialCanadianCoins = [
  { value: "1 dollar", year: "1995", name: "Peacekeeping Monument in Ottawa" , frontImage: "images/coins/Canada/1-dollar/canada-special-1995-peacekeeping-front.transparent.png", backImage: "images/coins/Canada/1-dollar/canada-special-1995-peacekeeping-back.transparent.png", frontDescription: "Queen Elizabeth II effigy", backDescription: "Peacekeeping Monument in Ottawa"},
  { value: "1 dollar", year: "2021", name: "125th Anniversary - Klondike Gold Rush" , frontImage: "images/coins/Canada/1-dollar/canada-special-2021-klondike-gold-rush-front.transparent.png", backImage: "images/coins/Canada/1-dollar/canada-special-2021-klondike-gold-rush-back.transparent.png", frontDescription: "Queen Elizabeth II effigy", backDescription: "Klondike Gold Rush commemorative design"},
  { value: "1 dollar", year: "2022", name: "175th Anniversary - Birth of Alexander Graham Bell - Coloured" , frontImage: "images/coins/Canada/1-dollar/canada-special-2022-alexander-graham-bell-coloured-front.transparent.png", backImage: "images/coins/Canada/1-dollar/canada-special-2022-alexander-graham-bell-coloured-back.transparent.png", frontDescription: "Queen Elizabeth II effigy", backDescription: "Alexander Graham Bell portrait with Silver Dart and HD-4 hydrofoil details"},
  { value: "1 dollar", year: "2012", name: "XXX Summer Olympic Games - London 2012" , frontImage: "images/coins/Canada/1-dollar/canada-special-2012-lucky-loonie-london-front.transparent.png", backImage: "images/coins/Canada/1-dollar/canada-special-2012-lucky-loonie-london-back.transparent.png", frontDescription: "Queen Elizabeth II effigy", backDescription: "Lucky Loonie Olympic commemorative design"},
  { value: "1 dollar", year: "2012", name: "100th Grey Cup" , frontImage: "images/coins/Canada/1-dollar/canada-special-2012-grey-cup-front.transparent.png", backImage: "images/coins/Canada/1-dollar/canada-special-2012-grey-cup-back.transparent.png", frontDescription: "Queen Elizabeth II effigy", backDescription: "100th Grey Cup commemorative design"},
  { value: "1 dollar", year: "2011", name: "Legendary Nature Peregrine Falcon" },
  { value: "1 dollar", year: "1994", name: "National War Memorial" , frontImage: "images/coins/Canada/1-dollar/canada-special-1994-national-war-memorial-front.transparent.png", backImage: "images/coins/Canada/1-dollar/canada-special-1994-national-war-memorial-back.transparent.png", frontDescription: "Queen Elizabeth II effigy", backDescription: "National War Memorial in Ottawa"},
  { value: "2 dollars", year: "2019", name: "75th Anniversary D-Day" , frontImage: "images/coins/Canada/2-dollars/canada-special-2019-d-day-front.transparent.png", backImage: "images/coins/Canada/2-dollars/canada-special-2019-d-day-back.transparent.png", frontDescription: "Queen Elizabeth II effigy", backDescription: "D-Day landing craft and Allied forces commemorative design"},
  { value: "2 dollars", year: "2017", name: "150th Anniversary of Canada - Dance of Spirits" , frontImage: "images/coins/Canada/2-dollars/canada-special-2017-dance-of-spirits-front.transparent.png", backImage: "images/coins/Canada/2-dollars/canada-special-2017-dance-of-spirits-back.transparent.png", frontDescription: "Queen Elizabeth II effigy with Canada 150 logo", backDescription: "Northern Lights Dance of the Spirits design"},
  { value: "2 dollars", year: "2020", name: "75th Anniversary of World War II" , frontImage: "images/coins/Canada/2-dollars/canada-special-2020-victory-front.transparent.png", backImage: "images/coins/Canada/2-dollars/canada-special-2020-victory-back.transparent.png", frontDescription: "Queen Elizabeth II effigy", backDescription: "Victory 5-cent inspired Second World War commemorative design"},
  { value: "2 dollars", year: "2022", name: "Black Toonie - Tribute to Queen Elizabeth II" , frontImage: "images/coins/Canada/2-dollars/canada-special-2022-honouring-queen-elizabeth-front.transparent.png", backImage: "images/coins/Canada/2-dollars/canada-special-2022-honouring-queen-elizabeth-back.transparent.png", frontDescription: "Queen Elizabeth II effigy with black mourning ring", backDescription: "Polar bear reverse with black mourning ring"},
  { value: "2 dollars", year: "2015", name: "100th Anniversary - In Flanders Fields Poem" , frontImage: "images/coins/Canada/2-dollars/canada-special-2015-in-flanders-fields-front.transparent.png", backImage: "images/coins/Canada/2-dollars/canada-special-2015-in-flanders-fields-back.transparent.png", frontDescription: "Queen Elizabeth II effigy", backDescription: "John McCrae writing In Flanders Fields with poppies"},
  { value: "2 dollars", year: "1608-2008", name: "400th Anniversary Founding of Quebec" , frontImage: "images/coins/Canada/2-dollars/canada-special-2008-quebec-city-front.transparent.png", backImage: "images/coins/Canada/2-dollars/canada-special-2008-quebec-city-back.transparent.png", frontDescription: "Queen Elizabeth II effigy", backDescription: "Quebec City 400th anniversary commemorative design"},
  { value: "2 dollars", year: "1967", name: "100th Anniversary of Canada - Centennial", frontImage: "images/coins/Canada/2-dollars/canada-1967-centennial-front.transparent.png", backImage: "images/coins/Canada/2-dollars/canada-1967-centennial-back.transparent.png", frontDescription: "Queen Elizabeth II effigy", backDescription: "Canada Centennial goose design" },
  { value: "2 dollars", year: "1921-2021", name: "Bluenose 100th Anniversary" },
  { value: "2 dollars", year: "2001", name: "International Year of Volunteers" },
  { value: "2 dollars", year: "1952-2002", name: "50th Anniversary Succession of Queen Elizabeth II" , frontImage: "images/coins/Canada/2-dollars/canada-special-2002-golden-jubilee-2-dollars-front.transparent.png", backImage: "images/coins/Canada/2-dollars/canada-special-2002-golden-jubilee-2-dollars-back.transparent.png", frontDescription: "Queen Elizabeth II Golden Jubilee effigy", backDescription: "Polar bear reverse design"},
  { value: "25 cents", year: "2007", name: "Vancouver 2010 Paralympic Games - Wheelchair Curling" , frontImage: "images/coins/Canada/25-cents/canada-special-2007-wheelchair-curling-front.transparent.png", backImage: "images/coins/Canada/25-cents/canada-special-2007-wheelchair-curling-back.transparent.png", frontDescription: "Queen Elizabeth II effigy with Paralympic Games text", backDescription: "Wheelchair curling player design"},
  { value: "10 cents", year: "1867-2017", name: "150th Anniversary of Canada - Wings of Peace" , frontImage: "images/coins/Canada/10-cents/canada-special-2017-wings-of-peace-front.transparent.png", backImage: "images/coins/Canada/10-cents/canada-special-2017-wings-of-peace-back.transparent.png", frontDescription: "Queen Elizabeth II effigy with Canada 150 logo", backDescription: "Dove with maple leaf Wings of Peace design"},
  { value: "5 cents", year: "1967-1992", name: "125th Anniversary of Canada" , frontImage: "images/coins/Canada/5-cents/canada-special-1992-confederation-5-cents-front.transparent.png", backImage: "images/coins/Canada/5-cents/canada-special-1992-confederation-5-cents-back.transparent.png", frontDescription: "Queen Elizabeth II effigy", backDescription: "Canada Confederation anniversary beaver design"},
  { value: "5 cents", year: "2002", name: "50th Anniversary - Succession of Queen Elizabeth II - 2002p" , frontImage: "images/coins/Canada/5-cents/canada-special-2002-golden-jubilee-5-cents-front.transparent.png", backImage: "images/coins/Canada/5-cents/canada-special-2002-golden-jubilee-5-cents-back.transparent.png", frontDescription: "Queen Elizabeth II Golden Jubilee effigy", backDescription: "Beaver reverse design"},
  { value: "1 cent", year: "2002", name: "50th Anniversary - Succession of Queen Elizabeth II - 2002 Copper Plated Zinc" , frontImage: "images/coins/Canada/1-cent/canada-special-2002-golden-jubilee-1-cent-front.transparent.png", backImage: "images/coins/Canada/1-cent/canada-special-2002-golden-jubilee-1-cent-back.transparent.png", frontDescription: "Queen Elizabeth II Golden Jubilee effigy", backDescription: "Maple twig reverse design"},
  { value: "1 cent", year: "1867-2017", name: "Canada 150" }
];

const banknoteInventory = [
  {
    "id": "iran-banknote-1950s-5rials-pahlavi-v1-1",
    "type": "banknote",
    "name": "Iran 5 rials Banknote (Pahlavi, 1950s, v1)",
    "country": "Iran",
    "year": "1950s",
    "collectionSet": "Iran Pahlavi Banknotes",
    "value": "5 rials",
    "material": "Paper banknote",
    "condition": "Not listed",
    "quantity": 1,
    "extraCopies": 0,
    "image": "images/banknotes/iran/banknote_iran_1950s_5rials_pahlavi_front_v1.jpg",
    "frontImage": "images/banknotes/iran/banknote_iran_1950s_5rials_pahlavi_front_v1.jpg",
    "backImage": "images/banknotes/iran/banknote_iran_1950s_5rials_pahlavi_back_v1.jpg",
    "frontDescription": "Front of the 5 rials Pahlavi banknote.",
    "backDescription": "Back of the 5 rials Pahlavi banknote.",
    "notes": ""
  },
  {
    "id": "iran-banknote-1950s-5rials-pahlavi-v2-2",
    "type": "banknote",
    "name": "Iran 5 rials Banknote (Pahlavi, 1950s, v2)",
    "country": "Iran",
    "year": "1950s",
    "collectionSet": "Iran Pahlavi Banknotes",
    "value": "5 rials",
    "material": "Paper banknote",
    "condition": "Not listed",
    "quantity": 1,
    "extraCopies": 0,
    "image": "images/banknotes/iran/banknote_iran_1950s_5rials_pahlavi_front_v2.jpg",
    "frontImage": "images/banknotes/iran/banknote_iran_1950s_5rials_pahlavi_front_v2.jpg",
    "backImage": "images/banknotes/iran/banknote_iran_1950s_5rials_pahlavi_back_v2.jpg",
    "frontDescription": "Front of the 5 rials Pahlavi banknote.",
    "backDescription": "Back of the 5 rials Pahlavi banknote.",
    "notes": ""
  },
  {
    "id": "iran-banknote-1960s-10rials-pahlavi-v1-1",
    "type": "banknote",
    "name": "Iran 10 rials Banknote (Pahlavi, 1960s, v1)",
    "country": "Iran",
    "year": "1960s",
    "collectionSet": "Iran Pahlavi Banknotes",
    "value": "10 rials",
    "material": "Paper banknote",
    "condition": "Not listed",
    "quantity": 1,
    "extraCopies": 0,
    "image": "images/banknotes/iran/banknote_iran_1960s_10rials_pahlavi_front_v1.jpg",
    "frontImage": "images/banknotes/iran/banknote_iran_1960s_10rials_pahlavi_front_v1.jpg",
    "backImage": "images/banknotes/iran/banknote_iran_1960s_10rials_pahlavi_back_v1.jpg",
    "frontDescription": "Front of the 10 rials Pahlavi banknote.",
    "backDescription": "Back of the 10 rials Pahlavi banknote.",
    "notes": ""
  },
  {
    "id": "iran-banknote-1960s-20rials-pahlavi-v1-1",
    "type": "banknote",
    "name": "Iran 20 rials Banknote (Pahlavi, 1960s, v1)",
    "country": "Iran",
    "year": "1960s",
    "collectionSet": "Iran Pahlavi Banknotes",
    "value": "20 rials",
    "material": "Paper banknote",
    "condition": "Not listed",
    "quantity": 1,
    "extraCopies": 0,
    "image": "images/banknotes/iran/banknote_iran_1960s_20rials_pahlavi_front_v1.jpg",
    "frontImage": "images/banknotes/iran/banknote_iran_1960s_20rials_pahlavi_front_v1.jpg",
    "backImage": "images/banknotes/iran/banknote_iran_1960s_20rials_pahlavi_back_v1.jpg",
    "frontDescription": "Front of the 20 rials Pahlavi banknote.",
    "backDescription": "Back of the 20 rials Pahlavi banknote.",
    "notes": ""
  },
  {
    "id": "iran-banknote-1960s-20rials-pahlavi-v2-2",
    "type": "banknote",
    "name": "Iran 20 rials Banknote (Pahlavi, 1960s, v2)",
    "country": "Iran",
    "year": "1960s",
    "collectionSet": "Iran Pahlavi Banknotes",
    "value": "20 rials",
    "material": "Paper banknote",
    "condition": "Not listed",
    "quantity": 1,
    "extraCopies": 0,
    "image": "images/banknotes/iran/banknote_iran_1960s_20rials_pahlavi_front_v2.jpg",
    "frontImage": "images/banknotes/iran/banknote_iran_1960s_20rials_pahlavi_front_v2.jpg",
    "backImage": "images/banknotes/iran/banknote_iran_1960s_20rials_pahlavi_back_v2.jpg",
    "frontDescription": "Front of the 20 rials Pahlavi banknote.",
    "backDescription": "Back of the 20 rials Pahlavi banknote.",
    "notes": ""
  },
  {
    "id": "iran-banknote-1960s-50rials-pahlavi-v1-1",
    "type": "banknote",
    "name": "Iran 50 rials Banknote (Pahlavi, 1960s, v1)",
    "country": "Iran",
    "year": "1960s",
    "collectionSet": "Iran Pahlavi Banknotes",
    "value": "50 rials",
    "material": "Paper banknote",
    "condition": "Not listed",
    "quantity": 1,
    "extraCopies": 0,
    "image": "images/banknotes/iran/banknote_iran_1960s_50rials_pahlavi_front_v1.jpg",
    "frontImage": "images/banknotes/iran/banknote_iran_1960s_50rials_pahlavi_front_v1.jpg",
    "backImage": "images/banknotes/iran/banknote_iran_1960s_50rials_pahlavi_back_v1.jpg",
    "frontDescription": "Front of the 50 rials Pahlavi banknote.",
    "backDescription": "Back of the 50 rials Pahlavi banknote.",
    "notes": ""
  },
  {
    "id": "iran-banknote-1960s-100rials-pahlavi-v1-1",
    "type": "banknote",
    "name": "Iran 100 rials Banknote (Pahlavi, 1960s, v1)",
    "country": "Iran",
    "year": "1960s",
    "collectionSet": "Iran Pahlavi Banknotes",
    "value": "100 rials",
    "material": "Paper banknote",
    "condition": "Not listed",
    "quantity": 1,
    "extraCopies": 0,
    "image": "images/banknotes/iran/banknote_iran_1960s_100rials_pahlavi_front_v1.jpg",
    "frontImage": "images/banknotes/iran/banknote_iran_1960s_100rials_pahlavi_front_v1.jpg",
    "backImage": "images/banknotes/iran/banknote_iran_1960s_100rials_pahlavi_back_v1.jpg",
    "frontDescription": "Front of the 100 rials Pahlavi banknote.",
    "backDescription": "Back of the 100 rials Pahlavi banknote.",
    "notes": ""
  },
  {
    "id": "iran-banknote-1960s-100rials-pahlavi-v2-2",
    "type": "banknote",
    "name": "Iran 100 rials Banknote (Pahlavi, 1960s, v2)",
    "country": "Iran",
    "year": "1960s",
    "collectionSet": "Iran Pahlavi Banknotes",
    "value": "100 rials",
    "material": "Paper banknote",
    "condition": "Not listed",
    "quantity": 1,
    "extraCopies": 0,
    "image": "images/banknotes/iran/banknote_iran_1960s_100rials_pahlavi_front_v2.jpg",
    "frontImage": "images/banknotes/iran/banknote_iran_1960s_100rials_pahlavi_front_v2.jpg",
    "backImage": "images/banknotes/iran/banknote_iran_1960s_100rials_pahlavi_back_v2.jpg",
    "frontDescription": "Front of the 100 rials Pahlavi banknote.",
    "backDescription": "Back of the 100 rials Pahlavi banknote.",
    "notes": ""
  },
  {
    "id": "iran-banknote-1970s-50rials-pahlavi-v1-1",
    "type": "banknote",
    "name": "Iran 50 rials Banknote (Pahlavi, 1970s, v1)",
    "country": "Iran",
    "year": "1970s",
    "collectionSet": "Iran Pahlavi Banknotes",
    "value": "50 rials",
    "material": "Paper banknote",
    "condition": "Not listed",
    "quantity": 1,
    "extraCopies": 0,
    "image": "images/banknotes/iran/banknote_iran_1970s_50rials_pahlavi_front_v1.jpg",
    "frontImage": "images/banknotes/iran/banknote_iran_1970s_50rials_pahlavi_front_v1.jpg",
    "backImage": "images/banknotes/iran/banknote_iran_1970s_50rials_pahlavi_back_v1.jpg",
    "frontDescription": "Front of the 50 rials Pahlavi banknote.",
    "backDescription": "Back of the 50 rials Pahlavi banknote.",
    "notes": ""
  },
  {
    "id": "iran-banknote-1970s-50rials-pahlavi-v2-2",
    "type": "banknote",
    "name": "Iran 50 rials Banknote (Pahlavi, 1970s, v2)",
    "country": "Iran",
    "year": "1970s",
    "collectionSet": "Iran Pahlavi Banknotes",
    "value": "50 rials",
    "material": "Paper banknote",
    "condition": "Not listed",
    "quantity": 1,
    "extraCopies": 0,
    "image": "images/banknotes/iran/banknote_iran_1970s_50rials_pahlavi_front_v2.jpg",
    "frontImage": "images/banknotes/iran/banknote_iran_1970s_50rials_pahlavi_front_v2.jpg",
    "backImage": "images/banknotes/iran/banknote_iran_1970s_50rials_pahlavi_back_v2.jpg",
    "frontDescription": "Front of the 50 rials Pahlavi banknote.",
    "backDescription": "Back of the 50 rials Pahlavi banknote.",
    "notes": ""
  },
  {
    "id": "iran-banknote-1970s-50rials-pahlavi-v2-duplicate",
    "type": "banknote",
    "name": "Iran 50 rials Banknote (Pahlavi, 1970s, v2, duplicate Word target)",
    "country": "Iran",
    "year": "1970s",
    "collectionSet": "Iran Pahlavi Banknotes",
    "value": "50 rials",
    "material": "Paper banknote",
    "condition": "Not listed",
    "quantity": 1,
    "extraCopies": 0,
    "image": "images/banknotes/iran/banknote_iran_1970s_50rials_pahlavi_front_v2-from-iran41.jpg",
    "frontImage": "images/banknotes/iran/banknote_iran_1970s_50rials_pahlavi_front_v2-from-iran41.jpg",
    "backImage": "images/banknotes/iran/banknote_iran_1970s_50rials_pahlavi_back_v2-from-iran42.jpg",
    "frontDescription": "Front of the 50 rials Pahlavi banknote.",
    "backDescription": "Back of the 50 rials Pahlavi banknote.",
    "notes": ""
  },
  {
    "id": "iran-banknote-1970s-50rials-pahlavi-v3-3",
    "type": "banknote",
    "name": "Iran 50 rials Banknote (Pahlavi, 1970s, v3)",
    "country": "Iran",
    "year": "1970s",
    "collectionSet": "Iran Pahlavi Banknotes",
    "value": "50 rials",
    "material": "Paper banknote",
    "condition": "Not listed",
    "quantity": 1,
    "extraCopies": 0,
    "image": "images/banknotes/iran/banknote_iran_1970s_50rials_pahlavi_front_v3.jpg",
    "frontImage": "images/banknotes/iran/banknote_iran_1970s_50rials_pahlavi_front_v3.jpg",
    "backImage": "images/banknotes/iran/banknote_iran_1970s_50rials_pahlavi_back_v3.jpg",
    "frontDescription": "Front of the 50 rials Pahlavi banknote.",
    "backDescription": "Back of the 50 rials Pahlavi banknote.",
    "notes": ""
  },
  {
    "id": "iran-banknote-1970s-100rials-pahlavi-v1-1",
    "type": "banknote",
    "name": "Iran 100 rials Banknote (Pahlavi, 1970s, v1)",
    "country": "Iran",
    "year": "1970s",
    "collectionSet": "Iran Pahlavi Banknotes",
    "value": "100 rials",
    "material": "Paper banknote",
    "condition": "Not listed",
    "quantity": 1,
    "extraCopies": 0,
    "image": "images/banknotes/iran/banknote_iran_1970s_100rials_pahlavi_front_v1.jpg",
    "frontImage": "images/banknotes/iran/banknote_iran_1970s_100rials_pahlavi_front_v1.jpg",
    "backImage": "images/banknotes/iran/banknote_iran_1970s_100rials_pahlavi_back_v1.jpg",
    "frontDescription": "Front of the 100 rials Pahlavi banknote.",
    "backDescription": "Back of the 100 rials Pahlavi banknote.",
    "notes": ""
  },
  {
    "id": "iran-banknote-1970s-200rials-pahlavi-v1-1",
    "type": "banknote",
    "name": "Iran 200 rials Banknote (Pahlavi, 1970s, v1)",
    "country": "Iran",
    "year": "1970s",
    "collectionSet": "Iran Pahlavi Banknotes",
    "value": "200 rials",
    "material": "Paper banknote",
    "condition": "Not listed",
    "quantity": 1,
    "extraCopies": 0,
    "image": "images/banknotes/iran/banknote_iran_1970s_200rials_pahlavi_front_v1.jpg",
    "frontImage": "images/banknotes/iran/banknote_iran_1970s_200rials_pahlavi_front_v1.jpg",
    "backImage": "images/banknotes/iran/banknote_iran_1970s_200rials_pahlavi_back_v1.jpg",
    "frontDescription": "Front of the 200 rials Pahlavi banknote.",
    "backDescription": "Back of the 200 rials Pahlavi banknote.",
    "notes": ""
  },
  {
    "id": "iran-banknote-1974-20rials-pahlavi-v1-1",
    "type": "banknote",
    "name": "Iran 20 rials Banknote (Pahlavi, 1974, v1)",
    "country": "Iran",
    "year": "1974",
    "collectionSet": "Iran Pahlavi Banknotes",
    "value": "20 rials",
    "material": "Paper banknote",
    "condition": "Not listed",
    "quantity": 1,
    "extraCopies": 0,
    "image": "images/banknotes/iran/banknote_iran_1974_20rials_pahlavi_front_v1.jpg",
    "frontImage": "images/banknotes/iran/banknote_iran_1974_20rials_pahlavi_front_v1.jpg",
    "backImage": "images/banknotes/iran/banknote_iran_1974_20rials_pahlavi_back_v1.jpg",
    "frontDescription": "Front of the 20 rials Pahlavi banknote.",
    "backDescription": "Back of the 20 rials Pahlavi banknote.",
    "notes": ""
  },
  {
    "id": "iran-banknote-1974-50rials-pahlavi-v1-1",
    "type": "banknote",
    "name": "Iran 50 rials Banknote (Pahlavi, 1974, v1)",
    "country": "Iran",
    "year": "1974",
    "collectionSet": "Iran Pahlavi Banknotes",
    "value": "50 rials",
    "material": "Paper banknote",
    "condition": "Not listed",
    "quantity": 1,
    "extraCopies": 0,
    "image": "images/banknotes/iran/banknote_iran_1974_50rials_pahlavi_front_v1.jpg",
    "frontImage": "images/banknotes/iran/banknote_iran_1974_50rials_pahlavi_front_v1.jpg",
    "backImage": "images/banknotes/iran/banknote_iran_1974_50rials_pahlavi_back_v1.jpg",
    "frontDescription": "Front of the 50 rials Pahlavi banknote.",
    "backDescription": "Back of the 50 rials Pahlavi banknote.",
    "notes": ""
  },
  {
    "id": "iran-banknote-1974-100rials-pahlavi-v1-1",
    "type": "banknote",
    "name": "Iran 100 rials Banknote (Pahlavi, 1974, v1)",
    "country": "Iran",
    "year": "1974",
    "collectionSet": "Iran Pahlavi Banknotes",
    "value": "100 rials",
    "material": "Paper banknote",
    "condition": "Not listed",
    "quantity": 1,
    "extraCopies": 0,
    "image": "images/banknotes/iran/banknote_iran_1974_100rials_pahlavi_front_v1.jpg",
    "frontImage": "images/banknotes/iran/banknote_iran_1974_100rials_pahlavi_front_v1.jpg",
    "backImage": "images/banknotes/iran/banknote_iran_1974_100rials_pahlavi_back_v1.jpg",
    "frontDescription": "Front of the 100 rials Pahlavi banknote.",
    "backDescription": "Back of the 100 rials Pahlavi banknote.",
    "notes": ""
  },
  {
    "id": "iran-banknote-1974-500rials-pahlavi-v1-1",
    "type": "banknote",
    "name": "Iran 500 rials Banknote (Pahlavi, 1974, v1)",
    "country": "Iran",
    "year": "1974",
    "collectionSet": "Iran Pahlavi Banknotes",
    "value": "500 rials",
    "material": "Paper banknote",
    "condition": "Not listed",
    "quantity": 1,
    "extraCopies": 0,
    "image": "images/banknotes/iran/banknote_iran_1974_500rials_pahlavi_front_v1.jpg",
    "frontImage": "images/banknotes/iran/banknote_iran_1974_500rials_pahlavi_front_v1.jpg",
    "backImage": "images/banknotes/iran/banknote_iran_1974_500rials_pahlavi_back_v1.jpg",
    "frontDescription": "Front of the 500 rials Pahlavi banknote.",
    "backDescription": "Back of the 500 rials Pahlavi banknote.",
    "notes": ""
  },
  {
    "id": "iran-banknote-1974-1000rials-pahlavi-v1-1",
    "type": "banknote",
    "name": "Iran 1,000 rials Banknote (Pahlavi, 1974, v1)",
    "country": "Iran",
    "year": "1974",
    "collectionSet": "Iran Pahlavi Banknotes",
    "value": "1,000 rials",
    "material": "Paper banknote",
    "condition": "Not listed",
    "quantity": 1,
    "extraCopies": 0,
    "image": "images/banknotes/iran/banknote_iran_1974_1000rials_pahlavi_front_v1.jpg",
    "frontImage": "images/banknotes/iran/banknote_iran_1974_1000rials_pahlavi_front_v1.jpg",
    "backImage": "images/banknotes/iran/banknote_iran_1974_1000rials_pahlavi_back_v1.jpg",
    "frontDescription": "Front of the 1,000 rials Pahlavi banknote.",
    "backDescription": "Back of the 1,000 rials Pahlavi banknote.",
    "notes": ""
  },
  {
    "id": "iran-banknote-1974-5000rials-pahlavi-v1-1",
    "type": "banknote",
    "name": "Iran 5,000 rials Banknote (Pahlavi, 1974, v1)",
    "country": "Iran",
    "year": "1974",
    "collectionSet": "Iran Pahlavi Banknotes",
    "value": "5,000 rials",
    "material": "Paper banknote",
    "condition": "Not listed",
    "quantity": 1,
    "extraCopies": 0,
    "image": "images/banknotes/iran/banknote_iran_1974_5000rials_pahlavi_front_v1.jpg",
    "frontImage": "images/banknotes/iran/banknote_iran_1974_5000rials_pahlavi_front_v1.jpg",
    "backImage": "images/banknotes/iran/banknote_iran_1974_5000rials_pahlavi_back_v1.jpg",
    "frontDescription": "Front of the 5,000 rials Pahlavi banknote.",
    "backDescription": "Back of the 5,000 rials Pahlavi banknote.",
    "notes": ""
  },
  {
    "id": "iran-banknote-1974-10000rials-pahlavi-v1-1",
    "type": "banknote",
    "name": "Iran 10,000 rials Banknote (Pahlavi, 1974, v1)",
    "country": "Iran",
    "year": "1974",
    "collectionSet": "Iran Pahlavi Banknotes",
    "value": "10,000 rials",
    "material": "Paper banknote",
    "condition": "Not listed",
    "quantity": 1,
    "extraCopies": 0,
    "image": "images/banknotes/iran/banknote_iran_1974_10000rials_pahlavi_front_v1.jpg",
    "frontImage": "images/banknotes/iran/banknote_iran_1974_10000rials_pahlavi_front_v1.jpg",
    "backImage": "images/banknotes/iran/banknote_iran_1974_10000rials_pahlavi_back_v1.jpg",
    "frontDescription": "Front of the 10,000 rials Pahlavi banknote.",
    "backDescription": "Back of the 10,000 rials Pahlavi banknote.",
    "notes": ""
  },
  {
    "id": "iran-banknote-1980s-100rials-islamic-v1-1",
    "type": "banknote",
    "name": "Iran 100 rials Banknote (Islamic Republic, 1980s, v1)",
    "country": "Iran",
    "year": "1980s",
    "collectionSet": "Iran Islamic Republic Banknotes",
    "value": "100 rials",
    "material": "Paper banknote",
    "condition": "Not listed",
    "quantity": 1,
    "extraCopies": 0,
    "image": "images/banknotes/iran/banknote_iran_1980s_100rials_islamic_front_v1.jpg",
    "frontImage": "images/banknotes/iran/banknote_iran_1980s_100rials_islamic_front_v1.jpg",
    "backImage": "images/banknotes/iran/banknote_iran_1980s_100rials_islamic_back_v1.jpg",
    "frontDescription": "Front of the 100 rials Islamic Republic banknote.",
    "backDescription": "Back of the 100 rials Islamic Republic banknote.",
    "notes": ""
  },
  {
    "id": "iran-banknote-1980s-200rials-islamic-v1-1",
    "type": "banknote",
    "name": "Iran 200 rials Banknote (Islamic Republic, 1980s, v1)",
    "country": "Iran",
    "year": "1980s",
    "collectionSet": "Iran Islamic Republic Banknotes",
    "value": "200 rials",
    "material": "Paper banknote",
    "condition": "Not listed",
    "quantity": 1,
    "extraCopies": 0,
    "image": "images/banknotes/iran/banknote_iran_1980s_200rials_islamic_front_v1.jpg",
    "frontImage": "images/banknotes/iran/banknote_iran_1980s_200rials_islamic_front_v1.jpg",
    "backImage": "images/banknotes/iran/banknote_iran_1980s_200rials_islamic_back_v1.jpg",
    "frontDescription": "Front of the 200 rials Islamic Republic banknote.",
    "backDescription": "Back of the 200 rials Islamic Republic banknote.",
    "notes": ""
  },
  {
    "id": "iran-banknote-1980s-500rials-islamic-v1-1",
    "type": "banknote",
    "name": "Iran 500 rials Banknote (Islamic Republic, 1980s, v1)",
    "country": "Iran",
    "year": "1980s",
    "collectionSet": "Iran Islamic Republic Banknotes",
    "value": "500 rials",
    "material": "Paper banknote",
    "condition": "Not listed",
    "quantity": 1,
    "extraCopies": 0,
    "image": "images/banknotes/iran/banknote_iran_1980s_500rials_islamic_front_v1.jpg",
    "frontImage": "images/banknotes/iran/banknote_iran_1980s_500rials_islamic_front_v1.jpg",
    "backImage": "images/banknotes/iran/banknote_iran_1980s_500rials_islamic_back_v1.jpg",
    "frontDescription": "Front of the 500 rials Islamic Republic banknote.",
    "backDescription": "Back of the 500 rials Islamic Republic banknote.",
    "notes": ""
  },
  {
    "id": "iran-banknote-1980s-1000rials-islamic-v1-1",
    "type": "banknote",
    "name": "Iran 1,000 rials Banknote (Islamic Republic, 1980s, v1)",
    "country": "Iran",
    "year": "1980s",
    "collectionSet": "Iran Islamic Republic Banknotes",
    "value": "1,000 rials",
    "material": "Paper banknote",
    "condition": "Not listed",
    "quantity": 1,
    "extraCopies": 0,
    "image": "images/banknotes/iran/banknote_iran_1980s_1000rials_islamic_front_v1.jpg",
    "frontImage": "images/banknotes/iran/banknote_iran_1980s_1000rials_islamic_front_v1.jpg",
    "backImage": "images/banknotes/iran/banknote_iran_1980s_1000rials_islamic_back_v1.jpg",
    "frontDescription": "Front of the 1,000 rials Islamic Republic banknote.",
    "backDescription": "Back of the 1,000 rials Islamic Republic banknote.",
    "notes": ""
  },
  {
    "id": "iran-banknote-1980s-5000rials-islamic-v1-1",
    "type": "banknote",
    "name": "Iran 5,000 rials Banknote (Islamic Republic, 1980s, v1)",
    "country": "Iran",
    "year": "1980s",
    "collectionSet": "Iran Islamic Republic Banknotes",
    "value": "5,000 rials",
    "material": "Paper banknote",
    "condition": "Not listed",
    "quantity": 1,
    "extraCopies": 0,
    "image": "images/banknotes/iran/banknote_iran_1980s_5000rials_islamic_front_v1.jpg",
    "frontImage": "images/banknotes/iran/banknote_iran_1980s_5000rials_islamic_front_v1.jpg",
    "backImage": "images/banknotes/iran/banknote_iran_1980s_5000rials_islamic_back_v1.jpg",
    "frontDescription": "Front of the 5,000 rials Islamic Republic banknote.",
    "backDescription": "Back of the 5,000 rials Islamic Republic banknote.",
    "notes": ""
  },
  {
    "id": "iran-banknote-1980s-10000rials-islamic-v1-1",
    "type": "banknote",
    "name": "Iran 10,000 rials Banknote (Islamic Republic, 1980s, v1)",
    "country": "Iran",
    "year": "1980s",
    "collectionSet": "Iran Islamic Republic Banknotes",
    "value": "10,000 rials",
    "material": "Paper banknote",
    "condition": "Not listed",
    "quantity": 1,
    "extraCopies": 0,
    "image": "images/banknotes/iran/banknote_iran_1980s_10000rials_islamic_front_v1.jpg",
    "frontImage": "images/banknotes/iran/banknote_iran_1980s_10000rials_islamic_front_v1.jpg",
    "backImage": "images/banknotes/iran/banknote_iran_1980s_10000rials_islamic_back_v1.jpg",
    "frontDescription": "Front of the 10,000 rials Islamic Republic banknote.",
    "backDescription": "Back of the 10,000 rials Islamic Republic banknote.",
    "notes": ""
  },
  {
    "id": "iran-banknote-1990s-2000rials-islamic-v2-2",
    "type": "banknote",
    "name": "Iran 2,000 rials Banknote (Islamic Republic, 1990s, v2)",
    "country": "Iran",
    "year": "1990s",
    "collectionSet": "Iran Islamic Republic Banknotes",
    "value": "2,000 rials",
    "material": "Paper banknote",
    "condition": "Not listed",
    "quantity": 1,
    "extraCopies": 0,
    "image": "images/banknotes/iran/banknote_iran_1990s_2000rials_islamic_front_v2.jpg",
    "frontImage": "images/banknotes/iran/banknote_iran_1990s_2000rials_islamic_front_v2.jpg",
    "backImage": "images/banknotes/iran/banknote_iran_1990s_2000rials_islamic_back_v2.jpg",
    "frontDescription": "Front of the 2,000 rials Islamic Republic banknote.",
    "backDescription": "Back of the 2,000 rials Islamic Republic banknote.",
    "notes": ""
  },
  {
    "id": "iran-banknote-1990s-5000rials-islamic-v1-1",
    "type": "banknote",
    "name": "Iran 5,000 rials Banknote (Islamic Republic, 1990s, v1)",
    "country": "Iran",
    "year": "1990s",
    "collectionSet": "Iran Islamic Republic Banknotes",
    "value": "5,000 rials",
    "material": "Paper banknote",
    "condition": "Not listed",
    "quantity": 1,
    "extraCopies": 0,
    "image": "images/banknotes/iran/banknote_iran_1990s_5000rials_islamic_front_v1.jpg",
    "frontImage": "images/banknotes/iran/banknote_iran_1990s_5000rials_islamic_front_v1.jpg",
    "backImage": "images/banknotes/iran/banknote_iran_1990s_5000rials_islamic_back_v1.jpg",
    "frontDescription": "Front of the 5,000 rials Islamic Republic banknote.",
    "backDescription": "Back of the 5,000 rials Islamic Republic banknote.",
    "notes": ""
  },
  {
    "id": "iran-banknote-2000s-1000rials-islamic-v2-2",
    "type": "banknote",
    "name": "Iran 1,000 rials Banknote (Islamic Republic, 2000s, v2)",
    "country": "Iran",
    "year": "2000s",
    "collectionSet": "Iran Islamic Republic Banknotes",
    "value": "1,000 rials",
    "material": "Paper banknote",
    "condition": "Not listed",
    "quantity": 1,
    "extraCopies": 0,
    "image": "images/banknotes/iran/banknote_iran_2000s_1000rials_islamic_front_v2.jpg",
    "frontImage": "images/banknotes/iran/banknote_iran_2000s_1000rials_islamic_front_v2.jpg",
    "backImage": "images/banknotes/iran/banknote_iran_2000s_1000rials_islamic_back_v2.jpg",
    "frontDescription": "Front of the 1,000 rials Islamic Republic banknote.",
    "backDescription": "Back of the 1,000 rials Islamic Republic banknote.",
    "notes": ""
  },
  {
    "id": "iran-banknote-2000s-2000rials-islamic-v1-1",
    "type": "banknote",
    "name": "Iran 2,000 rials Banknote (Islamic Republic, 2000s, v1)",
    "country": "Iran",
    "year": "2000s",
    "collectionSet": "Iran Islamic Republic Banknotes",
    "value": "2,000 rials",
    "material": "Paper banknote",
    "condition": "Not listed",
    "quantity": 1,
    "extraCopies": 0,
    "image": "images/banknotes/iran/banknote_iran_2000s_2000rials_islamic_front_v1.jpg",
    "frontImage": "images/banknotes/iran/banknote_iran_2000s_2000rials_islamic_front_v1.jpg",
    "backImage": "images/banknotes/iran/banknote_iran_2000s_2000rials_islamic_back_v1.jpg",
    "frontDescription": "Front of the 2,000 rials Islamic Republic banknote.",
    "backDescription": "Back of the 2,000 rials Islamic Republic banknote.",
    "notes": ""
  },
  {
    "id": "iran-banknote-2000s-10000rials-islamic-v2-2",
    "type": "banknote",
    "name": "Iran 10,000 rials Banknote (Islamic Republic, 2000s, v2)",
    "country": "Iran",
    "year": "2000s",
    "collectionSet": "Iran Islamic Republic Banknotes",
    "value": "10,000 rials",
    "material": "Paper banknote",
    "condition": "Not listed",
    "quantity": 1,
    "extraCopies": 0,
    "image": "images/banknotes/iran/banknote_iran_2000s_10000rials_islamic_front_v2.jpg",
    "frontImage": "images/banknotes/iran/banknote_iran_2000s_10000rials_islamic_front_v2.jpg",
    "backImage": "images/banknotes/iran/banknote_iran_2000s_10000rials_islamic_back_v2.jpg",
    "frontDescription": "Front of the 10,000 rials Islamic Republic banknote.",
    "backDescription": "Back of the 10,000 rials Islamic Republic banknote.",
    "notes": ""
  },
  {
    "id": "iran-banknote-2000s-20000rials-islamic-v1-1",
    "type": "banknote",
    "name": "Iran 20,000 rials Banknote (Islamic Republic, 2000s, v1)",
    "country": "Iran",
    "year": "2000s",
    "collectionSet": "Iran Islamic Republic Banknotes",
    "value": "20,000 rials",
    "material": "Paper banknote",
    "condition": "Not listed",
    "quantity": 1,
    "extraCopies": 0,
    "image": "images/banknotes/iran/banknote_iran_2000s_20000rials_islamic_front_v1.jpg",
    "frontImage": "images/banknotes/iran/banknote_iran_2000s_20000rials_islamic_front_v1.jpg",
    "backImage": "images/banknotes/iran/banknote_iran_2000s_20000rials_islamic_back_v1.jpg",
    "frontDescription": "Front of the 20,000 rials Islamic Republic banknote.",
    "backDescription": "Back of the 20,000 rials Islamic Republic banknote.",
    "notes": ""
  },
  {
    "id": "iran-banknote-2000s-50000rials-islamic-v1-1",
    "type": "banknote",
    "name": "Iran 50,000 rials Banknote (Islamic Republic, 2000s, v1)",
    "country": "Iran",
    "year": "2000s",
    "collectionSet": "Iran Islamic Republic Banknotes",
    "value": "50,000 rials",
    "material": "Paper banknote",
    "condition": "Not listed",
    "quantity": 1,
    "extraCopies": 0,
    "image": "images/banknotes/iran/banknote_iran_2000s_50000rials_islamic_front_v1.jpg",
    "frontImage": "images/banknotes/iran/banknote_iran_2000s_50000rials_islamic_front_v1.jpg",
    "backImage": "images/banknotes/iran/banknote_iran_2000s_50000rials_islamic_back_v1.jpg",
    "frontDescription": "Front of the 50,000 rials Islamic Republic banknote.",
    "backDescription": "Back of the 50,000 rials Islamic Republic banknote.",
    "notes": ""
  },
  {
    "id": "iran-banknote-2010s-10000rials-islamic-v3-3",
    "type": "banknote",
    "name": "Iran 10,000 rials Banknote (Islamic Republic, 2010s, v3)",
    "country": "Iran",
    "year": "2010s",
    "collectionSet": "Iran Islamic Republic Banknotes",
    "value": "10,000 rials",
    "material": "Paper banknote",
    "condition": "Not listed",
    "quantity": 1,
    "extraCopies": 0,
    "image": "images/banknotes/iran/banknote_iran_2010s_10000rials_islamic_front_v3.jpg",
    "frontImage": "images/banknotes/iran/banknote_iran_2010s_10000rials_islamic_front_v3.jpg",
    "backImage": "images/banknotes/iran/banknote_iran_2010s_10000rials_islamic_back_v3.jpg",
    "frontDescription": "Front of the 10,000 rials Islamic Republic banknote.",
    "backDescription": "Back of the 10,000 rials Islamic Republic banknote.",
    "notes": ""
  },
  {
    "id": "iran-banknote-2010s-100000rials-islamic-v1-1",
    "type": "banknote",
    "name": "Iran 100,000 rials Banknote (Islamic Republic, 2010s, v1)",
    "country": "Iran",
    "year": "2010s",
    "collectionSet": "Iran Islamic Republic Banknotes",
    "value": "100,000 rials",
    "material": "Paper banknote",
    "condition": "Not listed",
    "quantity": 1,
    "extraCopies": 0,
    "image": "images/banknotes/iran/banknote_iran_2010s_100000rials_islamic_front_v1.jpg",
    "frontImage": "images/banknotes/iran/banknote_iran_2010s_100000rials_islamic_front_v1.jpg",
    "backImage": "images/banknotes/iran/banknote_iran_2010s_100000rials_islamic_back_v1.jpg",
    "frontDescription": "Front of the 100,000 rials Islamic Republic banknote.",
    "backDescription": "Back of the 100,000 rials Islamic Republic banknote.",
    "notes": ""
  },
  {
    "id": "iran-banknote-2010s-100000rials-islamic-v2-2",
    "type": "banknote",
    "name": "Iran 100,000 rials Banknote (Islamic Republic, 2010s, v2)",
    "country": "Iran",
    "year": "2010s",
    "collectionSet": "Iran Islamic Republic Banknotes",
    "value": "100,000 rials",
    "material": "Paper banknote",
    "condition": "Not listed",
    "quantity": 1,
    "extraCopies": 0,
    "image": "images/banknotes/iran/banknote_iran_2010s_100000rials_islamic_front_v2.jpg",
    "frontImage": "images/banknotes/iran/banknote_iran_2010s_100000rials_islamic_front_v2.jpg",
    "backImage": "images/banknotes/iran/banknote_iran_2010s_100000rials_islamic_back_v2.jpg",
    "frontDescription": "Front of the 100,000 rials Islamic Republic banknote.",
    "backDescription": "Back of the 100,000 rials Islamic Republic banknote.",
    "notes": ""
  },
  {
    "id": "iran-banknote-2010s-500000rials-islamic-v1-1",
    "type": "banknote",
    "name": "Iran 500,000 rials Banknote (Islamic Republic, 2010s, v1)",
    "country": "Iran",
    "year": "2010s",
    "collectionSet": "Iran Islamic Republic Banknotes",
    "value": "500,000 rials",
    "material": "Paper banknote",
    "condition": "Not listed",
    "quantity": 1,
    "extraCopies": 0,
    "image": "images/banknotes/iran/banknote_iran_2010s_500000rials_islamic_front_v1.jpg",
    "frontImage": "images/banknotes/iran/banknote_iran_2010s_500000rials_islamic_front_v1.jpg",
    "backImage": "images/banknotes/iran/banknote_iran_2010s_500000rials_islamic_back_v1.jpg",
    "frontDescription": "Front of the 500,000 rials Islamic Republic banknote.",
    "backDescription": "Back of the 500,000 rials Islamic Republic banknote.",
    "notes": ""
  },
  {
    "id": "iran-banknote-2010s-1000000rials-islamic-v1-1",
    "type": "banknote",
    "name": "Iran 1,000,000 rials Banknote (Islamic Republic, 2010s, v1)",
    "country": "Iran",
    "year": "2010s",
    "collectionSet": "Iran Islamic Republic Banknotes",
    "value": "1,000,000 rials",
    "material": "Paper banknote",
    "condition": "Not listed",
    "quantity": 1,
    "extraCopies": 0,
    "image": "images/banknotes/iran/banknote_iran_2010s_1000000rials_islamic_front_v1.jpg",
    "frontImage": "images/banknotes/iran/banknote_iran_2010s_1000000rials_islamic_front_v1.jpg",
    "backImage": "images/banknotes/iran/banknote_iran_2010s_1000000rials_islamic_back_v1.jpg",
    "frontDescription": "Front of the 1,000,000 rials Islamic Republic banknote.",
    "backDescription": "Back of the 1,000,000 rials Islamic Republic banknote.",
    "notes": ""
  },
  {
    "id": "iran-banknote-2010s-1000000rials-islamic-v2-2",
    "type": "banknote",
    "name": "Iran 1,000,000 rials Banknote (Islamic Republic, 2010s, v2)",
    "country": "Iran",
    "year": "2010s",
    "collectionSet": "Iran Islamic Republic Banknotes",
    "value": "1,000,000 rials",
    "material": "Paper banknote",
    "condition": "Not listed",
    "quantity": 1,
    "extraCopies": 0,
    "image": "images/banknotes/iran/banknote_iran_2010s_1000000rials_islamic_front_v2.jpg",
    "frontImage": "images/banknotes/iran/banknote_iran_2010s_1000000rials_islamic_front_v2.jpg",
    "backImage": "images/banknotes/iran/banknote_iran_2010s_1000000rials_islamic_back_v2.jpg",
    "frontDescription": "Front of the 1,000,000 rials Islamic Republic banknote.",
    "backDescription": "Back of the 1,000,000 rials Islamic Republic banknote.",
    "notes": ""
  },
  {
    "id": "iran-banknote-2010s-2000000rials-islamic-v1-1",
    "type": "banknote",
    "name": "Iran 2,000,000 rials Banknote (Islamic Republic, 2010s, v1)",
    "country": "Iran",
    "year": "2010s",
    "collectionSet": "Iran Islamic Republic Banknotes",
    "value": "2,000,000 rials",
    "material": "Paper banknote",
    "condition": "Not listed",
    "quantity": 1,
    "extraCopies": 0,
    "image": "images/banknotes/iran/banknote_iran_2010s_2000000rials_islamic_front_v1.jpg",
    "frontImage": "images/banknotes/iran/banknote_iran_2010s_2000000rials_islamic_front_v1.jpg",
    "backImage": "images/banknotes/iran/banknote_iran_2010s_2000000rials_islamic_back_v1.jpg",
    "frontDescription": "Front of the 2,000,000 rials Islamic Republic banknote.",
    "backDescription": "Back of the 2,000,000 rials Islamic Republic banknote.",
    "notes": ""
  },
  {
    "id": "iran-banknote-2020s-500000rials-islamic-v2-2",
    "type": "banknote",
    "name": "Iran 500,000 rials Banknote (Islamic Republic, 2020s, v2)",
    "country": "Iran",
    "year": "2020s",
    "collectionSet": "Iran Islamic Republic Banknotes",
    "value": "500,000 rials",
    "material": "Paper banknote",
    "condition": "Not listed",
    "quantity": 1,
    "extraCopies": 0,
    "image": "images/banknotes/iran/banknote_iran_2020s_500000rials_islamic_front_v2.jpg",
    "frontImage": "images/banknotes/iran/banknote_iran_2020s_500000rials_islamic_front_v2.jpg",
    "backImage": "images/banknotes/iran/banknote_iran_2020s_500000rials_islamic_back_v2.jpg",
    "frontDescription": "Front of the 500,000 rials Islamic Republic banknote.",
    "backDescription": "Back of the 500,000 rials Islamic Republic banknote.",
    "notes": ""
  },
  {
    "id": "iran-banknote-2020s-500000rials-islamic-v3-3",
    "type": "banknote",
    "name": "Iran 500,000 rials Banknote (Islamic Republic, 2020s, v3)",
    "country": "Iran",
    "year": "2020s",
    "collectionSet": "Iran Islamic Republic Banknotes",
    "value": "500,000 rials",
    "material": "Paper banknote",
    "condition": "Not listed",
    "quantity": 1,
    "extraCopies": 0,
    "image": "images/banknotes/iran/banknote_iran_2020s_500000rials_islamic_front_v3.jpg",
    "frontImage": "images/banknotes/iran/banknote_iran_2020s_500000rials_islamic_front_v3.jpg",
    "backImage": "images/banknotes/iran/banknote_iran_2020s_500000rials_islamic_back_v3.jpg",
    "frontDescription": "Front of the 500,000 rials Islamic Republic banknote.",
    "backDescription": "Back of the 500,000 rials Islamic Republic banknote.",
    "notes": ""
  },
  {
    "id": "canada-banknote-1-dollar-pair-1",
    "type": "banknote",
    "name": "Canadian 1 dollar Banknote (pair 1)",
    "country": "Canada",
    "year": "Unknown year",
    "collectionSet": "Canada Banknotes",
    "value": "1 dollar",
    "material": "Paper / polymer banknote",
    "condition": "Not listed",
    "quantity": 1,
    "extraCopies": 0,
    "image": "images/banknotes/canada/F(1).jpg",
    "frontImage": "images/banknotes/canada/F(1).jpg",
    "backImage": "images/banknotes/canada/B(1).jpg",
    "frontDescription": "Front of the Canadian 1 dollar banknote.",
    "backDescription": "Back of the Canadian 1 dollar banknote.",
    "notes": ""
  },
  {
    "id": "canada-banknote-2-dollars-pair-2",
    "type": "banknote",
    "name": "Canadian 2 dollars Banknote (pair 2)",
    "country": "Canada",
    "year": "Unknown year",
    "collectionSet": "Canada Banknotes",
    "value": "2 dollars",
    "material": "Paper / polymer banknote",
    "condition": "Not listed",
    "quantity": 1,
    "extraCopies": 0,
    "image": "images/banknotes/canada/F(2).jpg",
    "frontImage": "images/banknotes/canada/F(2).jpg",
    "backImage": "images/banknotes/canada/B(2).jpg",
    "frontDescription": "Front of the Canadian 2 dollars banknote.",
    "backDescription": "Back of the Canadian 2 dollars banknote.",
    "notes": ""
  },
  {
    "id": "canada-banknote-5-dollars-pair-3",
    "type": "banknote",
    "name": "Canadian 5 dollars Banknote (pair 3)",
    "country": "Canada",
    "year": "Unknown year",
    "collectionSet": "Canada Banknotes",
    "value": "5 dollars",
    "material": "Paper / polymer banknote",
    "condition": "Not listed",
    "quantity": 1,
    "extraCopies": 0,
    "image": "images/banknotes/canada/F(3).jpg",
    "frontImage": "images/banknotes/canada/F(3).jpg",
    "backImage": "images/banknotes/canada/B(3).jpg",
    "frontDescription": "Front of the Canadian 5 dollars banknote.",
    "backDescription": "Back of the Canadian 5 dollars banknote.",
    "notes": ""
  },
  {
    "id": "canada-banknote-10-dollars-pair-4",
    "type": "banknote",
    "name": "Canadian 10 dollars Banknote (pair 4)",
    "country": "Canada",
    "year": "Unknown year",
    "collectionSet": "Canada Banknotes",
    "value": "10 dollars",
    "material": "Paper / polymer banknote",
    "condition": "Not listed",
    "quantity": 1,
    "extraCopies": 0,
    "image": "images/banknotes/canada/F(4).jpg",
    "frontImage": "images/banknotes/canada/F(4).jpg",
    "backImage": "images/banknotes/canada/B(4).jpg",
    "frontDescription": "Front of the Canadian 10 dollars banknote.",
    "backDescription": "Back of the Canadian 10 dollars banknote.",
    "notes": ""
  },
  {
    "id": "canada-banknote-20-dollars-pair-5",
    "type": "banknote",
    "name": "Canadian 20 dollars Banknote (pair 5)",
    "country": "Canada",
    "year": "Unknown year",
    "collectionSet": "Canada Banknotes",
    "value": "20 dollars",
    "material": "Paper / polymer banknote",
    "condition": "Not listed",
    "quantity": 1,
    "extraCopies": 0,
    "image": "images/banknotes/canada/F(5).jpg",
    "frontImage": "images/banknotes/canada/F(5).jpg",
    "backImage": "images/banknotes/canada/B(5).jpg",
    "frontDescription": "Front of the Canadian 20 dollars banknote.",
    "backDescription": "Back of the Canadian 20 dollars banknote.",
    "notes": ""
  },
  {
    "id": "canada-banknote-1-dollar-pair-6",
    "type": "banknote",
    "name": "Canadian 1 dollar Banknote (pair 6)",
    "country": "Canada",
    "year": "Unknown year",
    "collectionSet": "Canada Banknotes",
    "value": "1 dollar",
    "material": "Paper / polymer banknote",
    "condition": "Not listed",
    "quantity": 1,
    "extraCopies": 0,
    "image": "images/banknotes/canada/F(6).jpg",
    "frontImage": "images/banknotes/canada/F(6).jpg",
    "backImage": "images/banknotes/canada/B(6).jpg",
    "frontDescription": "Front of the Canadian 1 dollar banknote.",
    "backDescription": "Back of the Canadian 1 dollar banknote.",
    "notes": ""
  },
  {
    "id": "canada-banknote-2-dollars-pair-7",
    "type": "banknote",
    "name": "Canadian 2 dollars Banknote (pair 7)",
    "country": "Canada",
    "year": "Unknown year",
    "collectionSet": "Canada Banknotes",
    "value": "2 dollars",
    "material": "Paper / polymer banknote",
    "condition": "Not listed",
    "quantity": 1,
    "extraCopies": 0,
    "image": "images/banknotes/canada/F(7).jpg",
    "frontImage": "images/banknotes/canada/F(7).jpg",
    "backImage": "images/banknotes/canada/B(7).jpg",
    "frontDescription": "Front of the Canadian 2 dollars banknote.",
    "backDescription": "Back of the Canadian 2 dollars banknote.",
    "notes": ""
  },
  {
    "id": "canada-banknote-5-dollars-pair-8",
    "type": "banknote",
    "name": "Canadian 5 dollars Banknote (pair 8)",
    "country": "Canada",
    "year": "Unknown year",
    "collectionSet": "Canada Banknotes",
    "value": "5 dollars",
    "material": "Paper / polymer banknote",
    "condition": "Not listed",
    "quantity": 1,
    "extraCopies": 0,
    "image": "images/banknotes/canada/F(8).jpg",
    "frontImage": "images/banknotes/canada/F(8).jpg",
    "backImage": "images/banknotes/canada/B(8).jpg",
    "frontDescription": "Front of the Canadian 5 dollars banknote.",
    "backDescription": "Back of the Canadian 5 dollars banknote.",
    "notes": ""
  },
  {
    "id": "canada-banknote-10-dollars-pair-9",
    "type": "banknote",
    "name": "Canadian 10 dollars Banknote (pair 9)",
    "country": "Canada",
    "year": "Unknown year",
    "collectionSet": "Canada Banknotes",
    "value": "10 dollars",
    "material": "Paper / polymer banknote",
    "condition": "Not listed",
    "quantity": 1,
    "extraCopies": 0,
    "image": "images/banknotes/canada/F(9).jpg",
    "frontImage": "images/banknotes/canada/F(9).jpg",
    "backImage": "images/banknotes/canada/B(9).jpg",
    "frontDescription": "Front of the Canadian 10 dollars banknote.",
    "backDescription": "Back of the Canadian 10 dollars banknote.",
    "notes": ""
  },
  {
    "id": "canada-banknote-2-dollars-pair-10",
    "type": "banknote",
    "name": "Canadian 2 dollars Banknote (pair 10)",
    "country": "Canada",
    "year": "Unknown year",
    "collectionSet": "Canada Banknotes",
    "value": "2 dollars",
    "material": "Paper / polymer banknote",
    "condition": "Not listed",
    "quantity": 1,
    "extraCopies": 0,
    "image": "images/banknotes/canada/F(10).jpg",
    "frontImage": "images/banknotes/canada/F(10).jpg",
    "backImage": "images/banknotes/canada/B(10).jpg",
    "frontDescription": "Front of the Canadian 2 dollars banknote.",
    "backDescription": "Back of the Canadian 2 dollars banknote.",
    "notes": ""
  },
  {
    "id": "canada-banknote-5-dollars-pair-11",
    "type": "banknote",
    "name": "Canadian 5 dollars Banknote (pair 11)",
    "country": "Canada",
    "year": "Unknown year",
    "collectionSet": "Canada Banknotes",
    "value": "5 dollars",
    "material": "Paper / polymer banknote",
    "condition": "Not listed",
    "quantity": 1,
    "extraCopies": 0,
    "image": "images/banknotes/canada/F(11).jpg",
    "frontImage": "images/banknotes/canada/F(11).jpg",
    "backImage": "images/banknotes/canada/B(11).jpg",
    "frontDescription": "Front of the Canadian 5 dollars banknote.",
    "backDescription": "Back of the Canadian 5 dollars banknote.",
    "notes": ""
  },
  {
    "id": "canada-banknote-5-dollars-pair-12",
    "type": "banknote",
    "name": "Canadian 5 dollars Banknote (pair 12)",
    "country": "Canada",
    "year": "Unknown year",
    "collectionSet": "Canada Banknotes",
    "value": "5 dollars",
    "material": "Paper / polymer banknote",
    "condition": "Not listed",
    "quantity": 1,
    "extraCopies": 0,
    "image": "images/banknotes/canada/F(12).jpg",
    "frontImage": "images/banknotes/canada/F(12).jpg",
    "backImage": "images/banknotes/canada/B(12).jpg",
    "frontDescription": "Front of the Canadian 5 dollars banknote.",
    "backDescription": "Back of the Canadian 5 dollars banknote.",
    "notes": ""
  },
  {
    "id": "canada-banknote-20-dollars-pair-13",
    "type": "banknote",
    "name": "Canadian 20 dollars Banknote (pair 13)",
    "country": "Canada",
    "year": "Unknown year",
    "collectionSet": "Canada Banknotes",
    "value": "20 dollars",
    "material": "Paper / polymer banknote",
    "condition": "Not listed",
    "quantity": 1,
    "extraCopies": 0,
    "image": "images/banknotes/canada/F(13).jpg",
    "frontImage": "images/banknotes/canada/F(13).jpg",
    "backImage": "images/banknotes/canada/B(13).jpg",
    "frontDescription": "Front of the Canadian 20 dollars banknote.",
    "backDescription": "Back of the Canadian 20 dollars banknote.",
    "notes": ""
  },
  {
    "id": "canada-banknote-5-dollars-pair-14",
    "type": "banknote",
    "name": "Canadian 5 dollars Banknote (pair 14)",
    "country": "Canada",
    "year": "Unknown year",
    "collectionSet": "Canada Banknotes",
    "value": "5 dollars",
    "material": "Paper / polymer banknote",
    "condition": "Not listed",
    "quantity": 1,
    "extraCopies": 0,
    "image": "images/banknotes/canada/F(14).jpg",
    "frontImage": "images/banknotes/canada/F(14).jpg",
    "backImage": "images/banknotes/canada/B(14).jpg",
    "frontDescription": "Front of the Canadian 5 dollars banknote.",
    "backDescription": "Back of the Canadian 5 dollars banknote.",
    "notes": ""
  },
  {
    "id": "canada-banknote-20-dollars-pair-15",
    "type": "banknote",
    "name": "Canadian 20 dollars Banknote (pair 15)",
    "country": "Canada",
    "year": "Unknown year",
    "collectionSet": "Canada Banknotes",
    "value": "20 dollars",
    "material": "Paper / polymer banknote",
    "condition": "Not listed",
    "quantity": 1,
    "extraCopies": 0,
    "image": "images/banknotes/canada/F(15).jpg",
    "frontImage": "images/banknotes/canada/F(15).jpg",
    "backImage": "images/banknotes/canada/B(15).jpg",
    "frontDescription": "Front of the Canadian 20 dollars banknote.",
    "backDescription": "Back of the Canadian 20 dollars banknote.",
    "notes": ""
  },
  {
    "id": "canada-banknote-50-dollars-pair-16",
    "type": "banknote",
    "name": "Canadian 50 dollars Banknote (pair 16)",
    "country": "Canada",
    "year": "Unknown year",
    "collectionSet": "Canada Banknotes",
    "value": "50 dollars",
    "material": "Paper / polymer banknote",
    "condition": "Not listed",
    "quantity": 1,
    "extraCopies": 0,
    "image": "images/banknotes/canada/F(16).jpg",
    "frontImage": "images/banknotes/canada/F(16).jpg",
    "backImage": "images/banknotes/canada/B(16).jpg",
    "frontDescription": "Front of the Canadian 50 dollars banknote.",
    "backDescription": "Back of the Canadian 50 dollars banknote.",
    "notes": ""
  },
  {
    "id": "canada-banknote-100-dollars-pair-17",
    "type": "banknote",
    "name": "Canadian 100 dollars Banknote (pair 17)",
    "country": "Canada",
    "year": "Unknown year",
    "collectionSet": "Canada Banknotes",
    "value": "100 dollars",
    "material": "Paper / polymer banknote",
    "condition": "Not listed",
    "quantity": 1,
    "extraCopies": 0,
    "image": "images/banknotes/canada/F(17).jpg",
    "frontImage": "images/banknotes/canada/F(17).jpg",
    "backImage": "images/banknotes/canada/B(17).jpg",
    "frontDescription": "Front of the Canadian 100 dollars banknote.",
    "backDescription": "Back of the Canadian 100 dollars banknote.",
    "notes": ""
  }
];

function slugify(value) {
  return String(value)
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

function createRegularCoin(group, entry) {
  const [year, extraCopies = 0, specialName = "", frontImage = "", backImage = ""] = entry;
  const quantity = 1 + extraCopies;
  const namePrefix = specialName ? `${specialName} ` : "Canadian";

  return {
    id: `canada-coin-${slugify(group.value)}-${slugify(year)}-${slugify(specialName || "regular")}`,
    type: "coin",
    name: `${namePrefix} ${group.value} Coin`,
    country: "Canada",
    year,
    collectionSet: group.collectionSet,
    value: group.value,
    material: group.material,
    condition: "Not listed",
    quantity,
    extraCopies,
    image: frontImage,
    frontImage,
    backImage,
    notes: ""
  };
}

function createSpecialCoin(item, index) {
  return {
    id: `canada-special-${slugify(item.value)}-${slugify(item.year || "unknown")}-${index + 1}`,
    type: "coin",
    name: item.name,
    country: "Canada",
    year: item.year,
    collectionSet: "Special Collection",
    value: item.value,
    material: "Not listed",
    condition: "Not listed",
    quantity: 1,
    extraCopies: 0,
    image: item.frontImage || "",
    frontImage: item.frontImage || "",
    backImage: item.backImage || "",
    frontDescription: item.frontDescription || "",
    backDescription: item.backDescription || "",
    notes: "Special collection coin."
  };
}

window.collectionInventory = [
  ...regularCanadianCoins.flatMap((group) => group.items.map((entry) => createRegularCoin(group, entry))),
  ...specialCanadianCoins.map(createSpecialCoin),
  ...banknoteInventory
];






